"""Build the ultimate local TouchDesigner knowledge base.

This is the single source of truth that `chunks.jsonl` is generated from.
Every chunk is a self-contained, version-tagged fact (operator spec, Python
class, GLSL snippet, or workflow recipe) authored to be accurate and
hallucination-free. Re-runnable: regenerates `chunks.jsonl` deterministically.

Run:  python -m td_mcp.kb.build_kb
Then (optional, needs network + sentence-transformers):
      TD_MCP_DENSE=1 python -m td_mcp.kb.build_index
"""

import json
import os
import re

HERE = os.path.dirname(__file__)
OUT = os.path.join(HERE, "chunks.jsonl")

D_OC = "docs.derivative.ca/operators"
D_PY = "docs.derivative.ca/python"
D_GL = "docs.derivative.ca/glsl"
D_TU = "docs.derivative.ca/tutorials"


# ---------------------------------------------------------------------------
# Record helpers
# ---------------------------------------------------------------------------
def _clean(text):
    # collapse whitespace; keep one space between words
    return re.sub(r"\s+", " ", text.strip())


def op(family, title, text, tags, min_version="all", aliases=None, source=D_OC):
    return {
        "family": family,
        "title": title,
        "category": "operator",
        "source": source,
        "min_version": min_version,
        "tags": tags,
        "aliases": aliases or [],
        "text": _clean(text),
    }


def py(title, text, tags, min_version="all", aliases=None):
    return {
        "family": None,
        "title": title,
        "category": "python",
        "source": D_PY,
        "min_version": min_version,
        "tags": tags,
        "aliases": aliases or [],
        "text": _clean(text),
    }


def glsl(title, text, tags, min_version="all", aliases=None):
    return {
        "family": None,
        "title": title,
        "category": "glsl",
        "source": D_GL,
        "min_version": min_version,
        "tags": tags,
        "aliases": aliases or [],
        "text": _clean(text),
    }


def tut(title, text, tags, min_version="all", aliases=None, source=D_TU):
    return {
        "family": None,
        "title": title,
        "category": "tutorial",
        "source": source,
        "min_version": min_version,
        "tags": tags,
        "aliases": aliases or [],
        "text": _clean(text),
    }


RECORDS = []

# ===========================================================================
# TOP FAMILY
# ===========================================================================
RECORDS += [
    op("TOP", "Noise TOP",
       "Noise TOP generates images with noise patterns. Parameters: Type menu (Random, Turbulence, Sparse, Worley, Alligator, Fractal, Curl), Amplitude, Frequency, Seed, Monochrome, Animate Scope, Period. Use it as a displacement or pattern source. The Fractal type adds octaves for fractal noise. Connect its output into a Displace TOP or a Feedback/Level loop.",
       ["noise", "pattern", "random", "fractal"], aliases=["noise", "noise top"]),
    op("TOP", "Movie File In TOP",
       "Movie File In TOP reads a movie or image file into TOPs. Parameters: File (par.file, NOT filename), Play, Speed, Audio Rate, Cue, Trim Start/End, Caching, Preload. Python class is moviefileinTOP_Class. Common mistake: the parameter identifier is 'file' not 'filename'. Set in Python with op('moviein1').par.file = 'path'. Use 'Caching' = Automatic / Always / RAM / GPU to control memory.",
       ["video", "file", "image", "movie"], aliases=["movie", "moviefilein", "movie file in"]),
    op("TOP", "Blur TOP",
       "Blur TOP blurs an image. Parameters: Pre-Sharpen, Kernel menu (Box, Gaussian, Radial, etc.), Width, Height, Level, Aspect. Use before a Threshold TOP for a glow. For a simple Gaussian blur set Kernel to Gaussian and raise Level. Combine with a Level TOP for bloom.",
       ["blur", "filter", "glow"], aliases=["blur", "blur top", "gaussian"]),
    op("TOP", "Level TOP",
       "Level TOP adjusts brightness, contrast and gamma of an image. Parameters: Pre, Post, Gamma, Black, White, Mono, Invert. Essential in feedback loops to decay/offset the previous frame before recombining in a Feedback TOP. Post controls the overall brightness floor used for trails.",
       ["level", "contrast", "feedback", "gamma"], aliases=["level", "level top"]),
    op("TOP", "Feedback TOP",
       "Feedback TOP feeds its own previous output back as an input, creating trails and feedback loops. Wire a Level TOP (or transform) into Feedback's second input so each frame is offset/decayed before re-combining. Combine with Noise TOP and a Threshold TOP for classic generative feedback. Set 'Feedback' parameter to the TOP to loop.",
       ["feedback", "loop", "trails"], aliases=["feedback", "feedback top"]),
    op("TOP", "Render TOP",
       "Render TOP renders a 3D scene. It requires a Camera COMP, at least one Light COMP, and one or more Geometry COMPs connected to its inputs. Output is a 2D TOP. Set Camera and Light parameters to the relevant COMP paths. Add multiple geometry inputs for a scene. Anti-Alias and Render Pass parameters control quality.",
       ["render", "camera", "3d", "scene"], aliases=["render", "render top", "render3d"]),
    op("TOP", "Select TOP",
       "Select TOP references another TOP without cooking it directly (a 'pass-through' reference). Set the 'TOP' parameter to the source operator path. Useful to expose a TOP at a stable path while the source changes. Python: op('select1').par.top = 'source'.",
       ["select", "reference", "pass-through"], aliases=["select top", "selectop"]),
    op("TOP", "Transform TOP",
       "Transform TOP transforms an image with Translate, Rotate, Scale, Tile and Extend modes. It is a screen-space (2D) transform, unlike Transform SOP which is geometric. Use for UV offset / rotation of textures.",
       ["transform", "translate", "rotate", "uv"], aliases=["transform top", "transformtop"]),
    op("TOP", "Composite TOP",
       "Composite TOP combines two or more TOPs using an Operator menu (Over, Under, Inside, Add, Subtract, Multiply, Screen, Difference, etc.). Set the Operator parameter and the number of inputs. The default Over does alpha compositing.",
       ["composite", "over", "blend", "add"], aliases=["composite", "composite top"]),
    op("TOP", "Over TOP",
       "Over TOP composites one image over another with alpha. Input 0 is the foreground, input 1 the background. Faster and simpler than Composite TOP when only an 'over' is needed.",
       ["over", "composite", "alpha"], aliases=["over top"]),
    op("TOP", "Mix TOP",
       "Mix TOP cross-fades between two TOPs using the Cross Fade parameter (0..1). Useful for transitions between sources.",
       ["mix", "crossfade", "transition"], aliases=["mix top", "xfade"]),
    op("TOP", "Threshold TOP",
       "Threshold TOP converts an image to black/white (or a chosen color) based on a luminance threshold. Parameters: Threshold, Tolerance, Invert. Great after Noise/Blur for glows and particle-ish looks.",
       ["threshold", "mask", "binary"], aliases=["threshold top"]),
    op("TOP", "Ramp TOP",
       "Ramp TOP generates a gradient ramp. Parameters: Type (Horizontal, Vertical, Radial, Circular), Color 1/Color 2, Softness. Use as a mask or gradient source.",
       ["ramp", "gradient", "mask"], aliases=["ramp top", "ramp"]),
    op("TOP", "Gradient TOP",
       "Gradient TOP computes the gradient (derivative) magnitude/direction of an input image. Useful for edge detection and normal-map style effects.",
       ["gradient", "edge", "derivative"], aliases=["gradient top"]),
    op("TOP", "Constant TOP",
       "Constant TOP outputs a solid color. Parameters: Color, Alpha. Use as a background or color source. Python: op('constant1').par.colorr/g/b/a.",
       ["constant", "color", "background"], aliases=["constant top"]),
    op("TOP", "Circle TOP",
       "Circle TOP draws a circle (or ring) with Center, Radius, Color, Antialias. Inputs can define a mask via the 'Texture' input. Useful as a shape/particle base.",
       ["circle", "shape", "disk"], aliases=["circle top"]),
    op("TOP", "Rectangle TOP",
       "Rectangle TOP draws a rectangle with Center, Size, Color, Antialias. Use for bars, borders and UI elements.",
       ["rectangle", "shape", "box"], aliases=["rectangle top"]),
    op("TOP", "Text TOP",
       "Text TOP renders text to a texture. Parameters: Text, Font, Font Size, Align, Color, Background Color. Set the 'text' parameter in Python. Resolution parameter controls the output size. Use for labels, captions and HUDs.",
       ["text", "font", "label", "hud"], aliases=["text top", "textrender"]),
    op("TOP", "Video Device In TOP",
       "Video Device In TOP captures from a video input device (SDI, webcam, capture card). Parameters: Device, Signal, Resolution, Deinterlace. Requires a configured device in the Video Device In dialog. Common for live camera feeds.",
       ["video", "capture", "camera", "sdi"], aliases=["video device in", "videodevicein"]),
    op("TOP", "GLSL TOP",
       "GLSL TOP runs a custom GLSL shader on up to 4 input TOPs. Wire TOPs into inputs 0-3 and write a fragment shader (and optional vertex shader). Uniforms: sTD2DInputs[4], uTD2DInfos, and custom uniforms set via the 'Custom' parameter page. Output via 'fragColor'.",
       ["glsl", "shader", "fragment", "custom"], aliases=["glsl top", "glslshader"]),
    op("TOP", "Phong MAT",
       "Phong MAT is a material using the Phong lighting model (diffuse + specular). Parameters: Color, Diffuse, Specular, Roughness/Shininess, Environment Map, Maps page for textures. Apply to a Geometry COMP's Material parameter. Use with a Light COMP.",
       ["phong", "material", "lighting", "specular"], aliases=["phong mat", "phong"]),
    op("TOP", "PBR MAT",
       "PBR MAT is a physically-based material introduced for modern rendering. Parameters: Base Color, Metallic, Roughness, Emissive, Normal Map, Environment Map. More realistic than Phong MAT for lit scenes. Tagged as modern; workflows differ from Phong.",
       ["pbr", "material", "physically", "lighting"], aliases=["pbr mat", "pbr", "pbrmaterial"], min_version="2022.20000"),
    op("TOP", "Constant MAT",
       "Constant MAT renders geometry as a flat constant color (no lighting). Set Color and Alpha. Good for unlit overlays or mattes.",
       ["constant mat", "material", "flat"], aliases=["constant mat", "constantmat"]),
    op("TOP", "Depth TOP",
       "Depth TOP extracts the depth buffer from a Render TOP. Set the 'Render' parameter to the Render TOP. Output is grayscale depth, useful for fog, depth-of-field or post effects.",
       ["depth", "render", "zbuffer"], aliases=["depth top"]),
    op("TOP", "Edge TOP",
       "Edge TOP detects edges in an image using Sobel/Prewitt-style operators. Parameters: Method, Strength, Color. Use for outlines and stylized looks.",
       ["edge", "outline", "detect"], aliases=["edge top"]),
    op("TOP", "Mirror TOP",
       "Mirror TOP mirrors an image horizontally/vertically. Parameters: Mirror X, Mirror Y. Use for kaleidoscope effects combined with Transform TOP.",
       ["mirror", "flip", "symmetry"], aliases=["mirror top"]),
    op("TOP", "Lookup TOP",
       "Lookup TOP remaps an image's colors through a lookup table (LUT). Input 0 is the source, input 1 is the LUT. Use for color grading / palette mapping.",
       ["lookup", "lut", "grade", "remap"], aliases=["lookup top"]),
    op("TOP", "Displace TOP",
       "Displace TOP displaces an image using a second image as the displacement map. Parameters: Displace (the map input), Horizontal/Vertical Strength. Great for water / heat-haze using a Noise TOP as the map.",
       ["displace", "warp", "distort"], aliases=["displace top"]),
    op("TOP", "Crop TOP",
       "Crop TOP crops (or extends) an image using pixel or fraction Coordinates (Left/Right/Top/Bottom). Use to isolate regions or build grids.",
       ["crop", "region", "trim"], aliases=["crop top"]),
    op("TOP", "Fit TOP",
       "Fit TOP fits an image to a target resolution using a Fit parameter (Fill, Fit, Stretto/Cover, Horizontal, Vertical). Output resolution is set independently. Essential for aspect-ratio-correct layout.",
       ["fit", "aspect", "resize"], aliases=["fit top"]),
    op("TOP", "Flip TOP",
       "Flip TOP flips an image on X and/or Y. Parameters: Flip X, Flip Y. Simpler than Mirror when only a flip is needed.",
       ["flip", "mirror"], aliases=["flip top"]),
    op("TOP", "HSV Adjust TOP",
       "HSV Adjust TOP shifts Hue, Saturation and Value of an image. Parameters: Hue Adjust, Saturation Adjust, Value Adjust, with per-channel ranges. Use for color grading.",
       ["hsv", "color", "grade", "hue"], aliases=["hsv top", "hsvadjust"]),
    op("TOP", "Cache TOP",
       "Cache TOP stores the last cooked frame and can replay it. Parameters: Cache Size, Index. Useful to hold a still frame while the source updates, or step through a buffer.",
       ["cache", "hold", "buffer"], aliases=["cache top"]),
    op("TOP", "Null TOP",
       "Null TOP is a pass-through TOP used to anchor a stable output path and force a cook. It holds the last input frame. Commonly the final node before an Out TOP or a Select TOP reference.",
       ["null", "passthrough", "output"], aliases=["null top"]),
    op("TOP", "Out TOP",
       "Out TOP marks the final output of a TOP network. There can be multiple Out TOPs (out1..) referenced by parents. It is the boundary that exposed operators read.",
       ["out", "output", "terminal"], aliases=["out top", "outtop"]),
    op("TOP", "Touch In TOP",
       "Touch In TOP receives a TOP over the network from a Touch Out TOP (or another TouchDesigner instance). Parameters: Touch In (sync), Active. Use for multi-machine pipelines.",
       ["touch in", "network", "stream"], aliases=["touch in top"]),
    op("TOP", "Touch Out TOP",
       "Touch Out TOP sends a TOP over the network to a Touch In TOP. Set Active to broadcast. Pair with Touch In TOP for node-to-node streaming.",
       ["touch out", "network", "stream"], "stream", aliases=["touch out top"]),
    op("TOP", "Audio Spectrum TOP",
       "Audio Spectrum TOP visualizes an audio signal as a spectrum texture. Input is an Audio Device In CHOP / audio CHOP; output is a TOP showing frequency bins. Use for audio-reactive visuals.",
       ["audio", "spectrum", "visualizer", "fft"], aliases=["audio spectrum top", "audiospectrum"]),
    op("TOP", "Audio File In TOP",
       "Audio File In TOP plays an audio file and exposes its waveform/spectrum as a TOP. Parameters: File, Play, Speed. Pair with Audio Spectrum TOP for reactive visuals.",
       ["audio", "file", "music"], aliases=["audio file in top"]),
    op("TOP", "Luma TOP",
       "Luma TOP uses the luminance of one image as the alpha of another (or keys based on brightness). Parameters: Pre-multiply, Invert. Use for luminance keys.",
       ["luma", "key", "alpha", "luminance"], aliases=["luma top"]),
    op("TOP", "Monochrome TOP",
       "Monochrome TOP converts a color image to grayscale using per-channel weights. Parameters: Red/Green/Blue Weight. Use for B&W looks.",
       ["monochrome", "grayscale", "bw"], aliases=["monochrome top"]),
    op("TOP", "Chroma Key TOP",
       "Chroma Key TOP removes a chosen color (green/blue screen) from an image. Parameters: Key Color, Tolerance, Softness, Spill Suppression. Standard for green-screen compositing.",
       ["chroma", "key", "greenscreen", "spill"], aliases=["chroma key top", "chromakey"]),
    op("TOP", "Switch TOP",
       "Switch TOP selects one of several input TOPs based on the Index parameter (0..n). Use to swap sources programmatically or via CHOP export.",
       ["switch", "select", "index"], aliases=["switch top"]),
    op("TOP", "Cross TOP",
       "Cross TOP blends between two inputs with a Cross Fade parameter, like Mix TOP but optimized for two sources.",
       ["cross", "blend", "fade"], aliases=["cross top"]),
    op("TOP", "Sequence TOP",
       "Sequence TOP plays a series of input TOPs as frames (like a flipbook) driven by an Index. Parameters: Index, Length, Sequence Mode. Use for sprite/animation playbacks.",
       ["sequence", "frames", "flipbook"], aliases=["sequence top"]),
    op("TOP", "Billboard TOP",
       "Billboard TOP renders a TOP onto camera-facing quads in 3D, so sprites always face the camera. Used in particle/render pipelines.",
       ["billboard", "sprite", "camera-facing"], aliases=["billboard top"]),
    op("TOP", "Point Sprite TOP",
       "Point Sprite TOP renders points as sprites with size attenuation, commonly fed from SOP/POP point data in render pipelines.",
       ["point sprite", "particles", "sprite"], aliases=["point sprite top"]),
    op("TOP", "Particle TOP",
       "Particle GPU TOP simulates particles entirely on the GPU. Parameters: Number, Life, Speed, Force, plus feedback of the position buffer. Output position/color TOPs are rendered via a Point Sprite / Billboard TOP. High-performance alternative to POPs for simple particle systems.",
       ["particle", "gpu", "simulation"], aliases=["particle top"], min_version="2021.10000"),
    op("TOP", "Video Device Out TOP",
       "Video Device Out TOP sends a TOP to an output device (SDI/display). Parameters: Device, Signal, Output Resolution. Use for live show output / broadcast.",
       ["video out", "output", "sdi", "broadcast"], aliases=["video device out top"]),
]

# ===========================================================================
# CHOP FAMILY
# ===========================================================================
RECORDS += [
    op("CHOP", "LFO CHOP",
       "LFO CHOP generates oscillating channel values (sine, triangle, square, ramp, random). Parameters: Type, Frequency, Amplitude, Phase, Offset, Reset. Output is a channel you can export to a parameter with exportOPar. Use the 'Type' menu for waveform shape.",
       ["lfo", "oscillator", "animation", "wave"], aliases=["lfo", "lfocop"]),
    op("CHOP", "Constant CHOP",
       "Constant CHOP holds a static channel value you can animate or export. Parameters: Value (per-channel), Export. Commonly exported onto TOP/COMP parameters to drive motion. Set in Python: op('constant1').par.value0 = 0.5.",
       ["constant", "value", "export"], aliases=["constant chop"]),
    op("CHOP", "Audio Device In CHOP",
       "Audio Device In CHOP captures audio from an input device into CHOP channels (L/R etc.). Parameters: Device, Channels, Rate. Feed into Audio Spectrum CHOP or Math/Filter for audio-reactive visuals.",
       ["audio", "input", "sound", "mic"], aliases=["audio device in", "audioin"]),
    op("CHOP", "Audio Spectrum CHOP",
       "Audio Spectrum CHOP computes the FFT of an audio CHOP into frequency channels. Input is an audio CHOP (e.g. Audio Device In). Parameters: FFT Size, Frequency Bins, Window. Use for audio analysis.",
       ["audio", "spectrum", "fft", "analysis"], aliases=["audio spectrum chop"]),
    op("CHOP", "Math CHOP",
       "Math CHOP performs per-channel math: Channel Pre-Op (sqrt, abs, etc.), Multiply, Add, Combine Channels, Range mapping. Use to normalize audio (range 0..1) before export or to remap values.",
       ["math", "normalize", "range", "scale"], aliases=["math chop", "mathcop"]),
    op("CHOP", "Filter CHOP",
       "Filter CHOP smooths/low-pass filters channel data. Parameters: Filter (One-Pole, Box, Gaussian), Cutoff, Smooth. Use after Audio Device In to get a stable beat envelope.",
       ["filter", "smooth", "lowpass"], aliases=["filter chop"]),
    op("CHOP", "Oscillator CHOP",
       "Oscillator CHOP is a multi-waveform oscillator with phase control and is sample-rate accurate. Parameters: Type, Frequency, Amplitude, Phase. Similar to LFO but designed for audio-rate signals.",
       ["oscillator", "wave", "audio"], aliases=["oscillator chop"]),
    op("CHOP", "Noise CHOP",
       "Noise CHOP generates 1D/3D noise over time per channel. Parameters: Type (Random, Turbulence, etc.), Amplitude, Frequency, Seed, Animate. Use to drive organic motion.",
       ["noise", "random", "organic"], aliases=["noise chop"]),
    op("CHOP", "Trail CHOP",
       "Trail CHOP records the recent history of a channel into a buffer of N samples, useful for oscilloscope-style displays or motion trails. Parameters: Length, Clear. Export the output to a TOP via a CHOP to TOP conversion.",
       ["trail", "history", "buffer", "oscilloscope"], aliases=["trail chop"]),
    op("CHOP", "Speed CHOP",
       "Speed CHOP integrates a channel over time (or derivative with the Mode), producing a moving value from a rate. Parameters: Speed, Reset. Use to convert velocity into position.",
       ["speed", "integrate", "position"], aliases=["speed chop"]),
    op("CHOP", "Trigger CHOP",
       "Trigger CHOP generates a timed envelope (attack/hold/decay) when its input crosses a threshold. Parameters: Threshold, Attack, Hold, Decay. Great for beat/event pulses.",
       ["trigger", "envelope", "pulse", "beat"], aliases=["trigger chop"]),
    op("CHOP", "Count CHOP",
       "Count CHOP counts events: increments/decrements on rising edges or by step. Parameters: Count Mode, Step, Reset. Use for counters and sequencers.",
       ["count", "counter", "increment"], aliases=["count chop"]),
    op("CHOP", "Logic CHOP",
       "Logic CHOP performs boolean/comparison logic across channels: combine with AND/OR/XOR, or convert to On/Off with a Threshold. Parameters: Channel Pre-Op, Combine Channels, Convert. Use for state machines.",
       ["logic", "boolean", "compare"], aliases=["logic chop"]),
    op("CHOP", "Switch CHOP",
       "Switch CHOP selects one of several input CHOPs by the Index parameter. Use to route signal sources programmatically.",
       ["switch", "select", "route"], aliases=["switch chop"]),
    op("CHOP", "Merge CHOP",
       "Merge CHOP combines multiple CHOPs' channels. Parameters: Merge (Append, Replace, etc.), Channel Names. Use to assemble a multi-channel signal.",
       ["merge", "combine", "channels"], aliases=["merge chop"]),
    op("CHOP", "Select CHOP",
       "Select CHOP extracts a subset of channels from another CHOP. Parameters: CHOP, Channel Names. Use to isolate the channels you need.",
       ["select", "extract", "subset"], aliases=["select chop"]),
    op("CHOP", "Analyze CHOP",
       "Analyze CHOP computes statistics over channels: average, maximum, minimum, RMS, slope. Parameters: Function, Window. Use for level meters and beat detection helpers.",
       ["analyze", "average", "rms", "stats"], aliases=["analyze chop"]),
    op("CHOP", "Resample CHOP",
       "Resample CHOP changes the sample rate / frame mode of a CHOP. Parameters: Method, Sample Rate, Extend. Use to align audio-rate and animation-rate data.",
       ["resample", "sample", "rate"], aliases=["resample chop"]),
    op("CHOP", "Splice CHOP",
       "Splice CHOP inserts/replaces a section of one CHOP with another. Parameters: Trim, Insert. Useful for editing recorded performance data.",
       ["splice", "insert", "edit"], aliases=["splice chop"]),
    op("CHOP", "Envelope CHOP",
       "Envelope CHOP creates an ADSR-style envelope driven by trigger events. Parameters: Attack, Decay, Sustain, Release. Use for animation envelopes.",
       ["envelope", "adsr", "animation"], aliases=["envelope chop"]),
    op("CHOP", "Pattern CHOP",
       "Pattern CHOP generates repeating patterns (linear ramp, sine, square, etc.) across a defined length. Parameters: Type, Length, Speed. Use for stepping sequences.",
       ["pattern", "sequence", "ramp"], aliases=["pattern chop"]),
    op("CHOP", "Keyboard In CHOP",
       "Keyboard In CHOP reports key states (down/up) and values from the keyboard. Parameters: Key, Channel Names. Use for interactive control.",
       ["keyboard", "key", "input", "interactive"], aliases=["keyboard in", "keyboardin"]),
    op("CHOP", "Mouse In CHOP",
       "Mouse In CHOP reports mouse position (u,v) and buttons. Use for cursor-driven interaction on a perform window.",
       ["mouse", "input", "cursor", "interactive"], aliases=["mouse in", "mousein"]),
    op("CHOP", "OSC In CHOP",
       "OSC In CHOP receives Open Sound Control messages over UDP. Parameters: Network Address, Port, Message Direction. Each OSC address becomes a channel. Use for phone/tablet controllers.",
       ["osc", "open sound control", "udp", "network"], aliases=["osc in", "oscin"]),
    op("CHOP", "OSC Out CHOP",
       "OSC Out CHOP sends CHOP channels as OSC messages over UDP. Parameters: Network Address, Port. Pair with OSC In CHOP or external OSC apps.",
       ["osc", "out", "network", "udp"], aliases=["osc out", "oscout"]),
    op("CHOP", "MIDI In CHOP",
       "MIDI In CHOP receives MIDI notes/CC from a device. Parameters: Device, MIDI Port, Channel. Output channels represent note velocity, pitch, CC values. Use for instrument control.",
       ["midi", "in", "notes", "cc"], aliases=["midi in", "midiin"]),
    op("CHOP", "Timer CHOP",
       "Timer CHOP is a full-featured timing/sequencing engine: segments, cues, speed, go/stop. Parameters: Length, Speed, Play, Cue. The 'timer' callback drives show-control sequences. Very powerful for timelines.",
       ["timer", "sequence", "cue", "timeline", "show"], aliases=["timer chop"]),
    op("CHOP", "Beat CHOP",
       "Beat CHOP detects the beat/tempo from an audio input and outputs beats and BPM. Parameters: Sensitivity, Min/Max BPM. Use the 'beat' channel to trigger visuals.",
       ["beat", "bpm", "tempo", "audio"], aliases=["beat chop"]),
    op("CHOP", "Pulse CHOP",
       "Pulse CHOP outputs a single-sample pulse (0/1) at intervals or on events. Parameters: Pulse Rate, Pulse Width. Use to trigger actions on a schedule.",
       ["pulse", "trigger", "clock"], aliases=["pulse chop"]),
    op("CHOP", "SOP to CHOP",
       "SOP to CHOP extracts SOP attributes (positions, normals, colors) into CHOP channels for further processing. Parameters: SOP, Attributes. Use for geometry-driven data.",
       ["sop to chop", "extract", "attributes"], aliases=["sop to chop", "soptochop"]),
    op("CHOP", "CHOP to TOP",
       "CHOP to TOP converts CHOP channels into a TOP image (each channel a row or column). Parameters: Format, Rows/Cols. Use to visualize data or feed shaders.",
       ["chop to top", "visualize", "convert"], aliases=["chop to top", "choptotop"]),
    op("CHOP", "DAT to CHOP",
       "DAT to CHOP converts table/cell data from a DAT into CHOP channels. Parameters: DAT, First Column Is, By Row/Column. Use to drive channels from spreadsheets.",
       ["dat to chop", "convert", "table"], aliases=["dat to chop", "dattocop"]),
    op("CHOP", "Evaluate CHOP",
       "Evaluate CHOP computes expressions per-sample across input channels. Parameters: Expressions (one per channel). Use for custom math/conditionals on signals.",
       ["evaluate", "expression", "math"], aliases=["evaluate chop"]),
    op("CHOP", "Lookup CHOP",
       "Lookup CHOP remaps an input index channel through a lookup table (another CHOP) — like a 1D sampler. Parameters: Index, Lookup CHOP. Use for wavetable/animation retiming.",
       ["lookup", "remap", "index", "wavetable"], aliases=["lookup chop"]),
    op("CHOP", "Wave CHOP",
       "Wave CHOP generates an audio-rate waveform (sine/square/saw/triangle) with frequency modulation. Used for synthesis and audio-rate modulation sources.",
       ["wave", "oscillator", "audio", "synth"], aliases=["wave chop"]),
]

# ===========================================================================
# SOP FAMILY
# ===========================================================================
RECORDS += [
    op("SOP", "Box SOP",
       "Box SOP creates a box primitive. Parameters: Size (sx,sy,sz), Center, Divisions (sx,sy,sz), Type (Polygon/Bezier/NURBS). The base primitive for most 3D scenes.",
       ["box", "cube", "primitive", "geometry"], aliases=["box sop"]),
    op("SOP", "Sphere SOP",
       "Sphere SOP creates a sphere. Parameters: Primitive Type (Polygon/Bezier/NURBS), Radius, Frequency/Rows, Orbit. Use as planets, balls, particles base.",
       ["sphere", "ball", "primitive"], aliases=["sphere sop"]),
    op("SOP", "Grid SOP",
       "Grid SOP creates a planar grid of points/primitives. Parameters: Size, Rows, Cols, Center. Use for terrain, displacement surfaces, and point clouds.",
       ["grid", "plane", "terrain", "points"], aliases=["grid sop"]),
    op("SOP", "Tube SOP",
       "Tube SOP creates a tube (cylinder with caps or open). Parameters: Radius, Height, Rows, Caps. Use for columns, pipes and procedural shapes.",
       ["tube", "cylinder", "pipe"], aliases=["tube sop"]),
    op("SOP", "Torus SOP",
       "Torus SOP creates a donut/torus. Parameters: Radius (major/minor), Rows, Columns. Use for rings and Orbit-style visuals.",
       ["torus", "donut", "ring"], aliases=["torus sop"]),
    op("SOP", "Circle SOP",
       "Circle SOP creates a circle/disk. Parameters: Radius, Center, Rows, Type. Use as a 2D primitive or particle disk.",
       ["circle", "disk", "2d"], aliases=["circle sop"]),
    op("SOP", "Rectangle SOP",
       "Rectangle SOP creates a rectangle in the XY plane. Parameters: Size, Center, Rows/Cols. Use for panels and flat geometry.",
       ["rectangle", "plane", "flat"], aliases=["rectangle sop"]),
    op("SOP", "Line SOP",
       "Line SOP creates a line of N points between two endpoints. Parameters: Begin/End, Points. Use for paths and connecting geometry.",
       ["line", "path", "points"], aliases=["line sop"]),
    op("SOP", "Null SOP",
       "Null SOP is a pass-through SOP used to anchor a stable output path and control cooking. Standard terminal before an Out SOP or a Geometry COMP's 'Geometry' parameter.",
       ["null", "passthrough", "output"], aliases=["null sop"]),
    op("SOP", "Merge SOP",
       "Merge SOP combines multiple SOP streams into one. Parameters: Merge, Consolidate. Use to assemble complex geometry from primitives.",
       ["merge", "combine", "join"], aliases=["merge sop"]),
    op("SOP", "Switch SOP",
       "Switch SOP selects one of several input SOPs by the Index parameter. Use to swap geometry programmatically.",
       ["switch", "select", "index"], aliases=["switch sop"]),
    op("SOP", "Transform SOP",
       "Transform SOP moves, rotates and scales geometry. Parameters: Translate, Rotate, Scale, Pivot. Input is a SOP; output is the transformed geometry. Chain multiple for compound transforms.",
       ["transform", "translate", "rotate", "scale"], aliases=["transform sop"]),
    op("SOP", "Copy SOP",
       "Copy SOP replicates a source SOP many times, driven by a template (points of another SOP). Parameters: Number of Copies (or use template points), Transform. The classic instancing primitive before the instancing system.",
       ["copy", "instance", "replicate", "duplicate"], aliases=["copy sop"]),
    op("SOP", "Metaball SOP",
       "Metaball SOP creates smooth blobby surfaces from metaball points. Parameters: Radius, Exponent, Threshold. Use for organic/liquid looks.",
       ["metaball", "blob", "organic"], aliases=["metaball sop"]),
    op("SOP", "Font SOP",
       "Font SOP generates 3D text geometry from a string. Parameters: Text, Font, Font Size, Extrude. Use for 3D titles.",
       ["font", "text", "3d", "title"], aliases=["font sop"]),
    op("SOP", "Text SOP",
       "Text SOP creates flat (2D) text geometry. Parameters: Text, Font, Font Size, Spacing. Use for labels in 3D space (often rendered with a Constant/Phong MAT). Note: 3D extruded text uses Font SOP.",
       ["text", "label", "2d"], aliases=["text sop"]),
    op("SOP", "Extrude SOP",
       "Extrude SOP extrudes a 2D profile (e.g. from a Font/Text SOP) into 3D along a path. Parameters: Depth, Cap, Divisions. Use for 3D letters and shapes.",
       ["extrude", "3d", "depth"], aliases=["extrude sop"]),
    op("SOP", "Revolve SOP",
       "Revolve SOP revolves a 2D profile around an axis to create lathe-style geometry. Parameters: Axis, Start/End Angle, Divisions. Use for vases, bottles, rings.",
       ["revolve", "lathe", "surface"], aliases=["revolve sop"]),
    op("SOP", "Skin SOP",
       "Skin SOP binds geometry to a skeleton for skeletal deformation. Parameters: Capture, Deform. Used in character/object deformation pipelines.",
       ["skin", "skeleton", "deform"], aliases=["skin sop"]),
    op("SOP", "Noise SOP",
       "Noise SOP displaces geometry points using 3D noise. Parameters: Transform (amp per axis), Noise Type, Frequency, Seed. Create organic deformed surfaces.",
       ["noise", "displace", "deform", "organic"], aliases=["noise sop"]),
    op("SOP", "Point SOP",
       "Point SOP edits per-point attributes (position, color, normals, scale) via expressions or parameters. Parameters: Position, Color, Scale. Core node for procedural geometry.",
       ["point", "attribute", "position", "color"], aliases=["point sop"]),
    op("SOP", "Facet SOP",
       "Facet SOP controls face smoothness / consolidation and computes normals. Parameters: Cusp Polygons, Faceting, Compute Normals. Use to smooth or harden shading.",
       ["facet", "normals", "smooth", "cusp"], aliases=["facet sop"]),
    op("SOP", "Join SOP",
       "Join SOP connects/bridges multiple SOP surfaces into one continuous surface. Parameters: Tolerance, Consolidate. Use to weld separate primitives.",
       ["join", "weld", "bridge"], aliases=["join sop"]),
    op("SOP", "Divide SOP",
       "Divide SOP subdivides/retessellates polygons into triangles or smaller polygons. Parameters: Triangulate, Maximum Edges. Use to clean up geometry for deformation.",
       ["divide", "triangulate", "tessellate"], aliases=["divide sop"]),
    op("SOP", "Group SOP",
       "Group SOP defines a named subset of primitives/points for later operations. Parameters: Group Name, Entity, Pattern. Use to target specific parts of geometry.",
       ["group", "subset", "selection"], aliases=["group sop"]),
    op("SOP", "Delete SOP",
       "Delete SOP removes primitives/points by pattern or group. Parameters: Entity, Operation, Pattern. Use to carve geometry.",
       ["delete", "remove", "prune"], aliases=["delete sop"]),
    op("SOP", "Attribute Create SOP",
       "Attribute Create SOP adds or modifies geometry attributes (color, uv, custom). Parameters: Attribute Name, Type, Value. Essential for feeding shaders and instances.",
       ["attribute", "create", "color", "uv"], aliases=["attribute create sop"]),
    op("SOP", "Peak SOP",
       "Peak SOP holds the maximum value of an attribute over time (with decay). Useful to highlight peaks in motion. Parameters: Peak, Decay.",
       ["peak", "decay", "max"], aliases=["peak sop"]),
    op("SOP", "Carve SOP",
       "Carve SOP slices a primitive at a parameter position (like extracting a cross-section). Parameters: First/Second U/V, Extract. Use for reveals and section cuts.",
       ["carve", "slice", "section"], aliases=["carve sop"]),
    op("SOP", "Dissolve SOP",
       "Dissolve SOP gradually removes/relaxes edges based on a threshold, blending between two states. Parameters: Dissolve, Tolerance. Use for morphing/transitions.",
       ["dissolve", "morph", "transition"], aliases=["dissolve sop"]),
    op("SOP", "Wireframe SOP",
       "Wireframe SOP renders only the edges of geometry as lines. Parameters: Wire Frame, Use Corner. Use for holographic/blueprint looks.",
       ["wireframe", "edges", "lines"], aliases=["wireframe sop"]),
    op("SOP", "Sort SOP",
       "Sort SOP reorders primitives/points by criteria (position, random, attribute). Parameters: Sort By, Random Seed. Use for procedural organization and animation order.",
       ["sort", "order", "random"], aliases=["sort sop"]),
]

# ===========================================================================
# DAT FAMILY
# ===========================================================================
RECORDS += [
    op("DAT", "Table DAT",
       "Table DAT stores a 2D grid of text cells (spreadsheet). Access cells: op('table1')['r1','c1'].value or .val. Edit via .setCell() / .setRow(). Common data store for scripts.",
       ["table", "spreadsheet", "cells", "data"], aliases=["table", "table dat"]),
    op("DAT", "Text DAT",
       "Text DAT stores free-form multi-line text and can execute as a script (Python) or hold GLSL/JSON. Members: .text, .run(), .storage. Set the 'lang' parameter to 'python' to run it. The classic place to put a TouchDesigner script.",
       ["text", "script", "python", "dat"], aliases=["text dat", "script"]),
    op("DAT", "Script DAT",
       "Script DAT runs Python each frame or on demand via the run() callback. Members: .text, .run(), .storage. Python class scriptDAT_Class. For periodic execution set the Execute parameter (On Start, On Frame Start, On Frame End, etc.).",
       ["script", "python", "dat", "callback"], aliases=["script dat"]),
    op("DAT", "Web Client DAT",
       "Web Client DAT performs HTTP requests from inside TouchDesigner. Use op('web1').fetch(url, method) and handle responses in the onResponse callback. Set callbacks: onResponse, onError. Useful for talking to REST APIs, OSC bridges, or local MCP endpoints.",
       ["http", "api", "request", "rest", "web"], aliases=["web client", "webclient", "http dat"]),
    op("DAT", "OSC In DAT",
       "OSC In DAT receives OSC messages and formats them as table rows. Parameters: Network Address, Port, Address Scope. Each message becomes a row with address + arguments. Use for custom OSC parsing.",
       ["osc", "in", "network", "dat"], aliases=["osc in dat", "oscin dat"]),
    op("DAT", "OSC Out DAT",
       "OSC Out DAT sends OSC messages from table rows. Parameters: Network Address, Port. Pair with OSC In DAT or external OSC apps.",
       ["osc", "out", "network", "dat"], aliases=["osc out dat"]),
    op("DAT", "MIDI In DAT",
       "MIDI In DAT receives raw MIDI events as table rows (note on/off, CC, pitch). Parameters: Device, Channel. Use for fine-grained MIDI handling beyond MIDI In CHOP.",
       ["midi", "in", "events", "dat"], aliases=["midi in dat"]),
    op("DAT", "UDP In DAT",
       "UDP In DAT receives raw UDP packets as text rows. Parameters: Network Address, Port, Protocol. Use for custom network protocols and sensors.",
       ["udp", "in", "network", "dat"], aliases=["udp in dat"]),
    op("DAT", "UDP Out DAT",
       "UDP Out DAT sends raw UDP packets (text) to an address. Parameters: Network Address, Port. Use for sending data to external systems.",
       ["udp", "out", "network", "dat"], aliases=["udp out dat"]),
    op("DAT", "TCP/IP DAT",
       "TCP/IP DAT maintains a TCP client connection, sending/receiving text packets. Parameters: Address, Port, Connect. Use for robust socket communication.",
       ["tcp", "network", "socket", "dat"], aliases=["tcp dat", "tcpip dat"]),
    op("DAT", "Serial DAT",
       "Serial DAT reads/writes a serial port. Parameters: Port, Baud Rate. Use for Arduino and other serial hardware.",
       ["serial", "arduino", "hardware", "dat"], aliases=["serial dat"]),
    op("DAT", "File In DAT",
       "File In DAT reads a text/table file from disk and updates on change. Parameters: File, Rows. Use to load CSV/JSON configuration.",
       ["file", "in", "read", "csv", "dat"], aliases=["file in dat"]),
    op("DAT", "File Out DAT",
       "File Out DAT writes its contents to a file on disk. Parameters: File, Write. Use for logging and exporting data.",
       ["file", "out", "write", "dat"], aliases=["file out dat"]),
    op("DAT", "Execute DAT",
       "Execute DAT runs Python on project events: On Start, On Exit, On Frame Start/End, On Movie Start/End. Use for global lifecycle hooks.",
       ["execute", "events", "lifecycle", "python"], aliases=["execute dat"]),
    op("DAT", "Panel Execute DAT",
       "Panel Execute DAT runs Python on UI panel events (value change, click, rollover) of a specified panel component. Parameters: Panel, Events. Use for custom widget behavior.",
       ["panel", "execute", "ui", "events"], aliases=["panel execute dat"]),
    op("DAT", "CHOP Execute DAT",
       "CHOP Execute DAT runs Python when CHOP channels cross thresholds (On Value Change, On CHOP Start/End). Parameters: CHOP, Channels. Use for event triggers.",
       ["chop", "execute", "trigger", "events"], aliases=["chop execute dat"]),
    op("DAT", "Parameter Execute DAT",
       "Parameter Execute DAT runs Python when parameters change (On Value Change, On Pulse). Parameters: Ops, Parameters. Use to react to UI/parameter edits.",
       ["parameter", "execute", "change", "events"], aliases=["parameter execute dat"]),
    op("DAT", "Select DAT",
       "Select DAT references rows/columns of another DAT without copying. Parameters: DAT, Select Rows/Columns. Use to expose a stable subset.",
       ["select", "reference", "subset"], aliases=["select dat"]),
    op("DAT", "Folder DAT",
       "Folder DAT lists files/folders in a directory as rows. Parameters: Folder, File Mask, Recursive. Use to build media playlists and asset browsers.",
       ["folder", "files", "list", "browser"], aliases=["folder dat"]),
    op("DAT", "Multi Touch In DAT",
       "Multi Touch In DAT receives tuio/multitouch events as rows. Parameters: Port. Use for touch walls and interactive surfaces.",
       ["multitouch", "touch", "tuio", "interactive"], aliases=["multi touch in dat"]),
    op("DAT", "Blob Track DAT",
       "Blob Track DAT performs background-subtraction blob tracking from a TOP (e.g. a camera). Outputs tracked blob data as table rows. Use for interactive installations.",
       ["blob", "track", "camera", "interactive"], aliases=["blob track dat"]),
    op("DAT", "Kinect DAT",
       "Kinect DAT receives skeleton/joint data from a Microsoft Kinect. Parameters: Sensor, Tracking. Use for body-tracking interactives.",
       ["kinect", "skeleton", "tracking", "body"], aliases=["kinect dat"]),
    op("DAT", "FIFO DAT",
       "FIFO DAT is a first-in-first-out queue of rows with a maximum length. Use to buffer event logs and sensor streams.",
       ["fifo", "queue", "buffer"], aliases=["fifo dat"]),
    op("DAT", "Oscillator DAT",
       "Oscillator DAT generates a table of sine-wave sample values for audio-rate synthesis and wavetable use.",
       ["oscillator", "audio", "wavetable"], aliases=["oscillator dat"]),
]

# ===========================================================================
# COMP FAMILY
# ===========================================================================
RECORDS += [
    op("COMP", "Container COMP",
       "Container COMP is a panel/UI container that holds children and can be a 2D UI panel or a 3D object. Parameters: Background, Borders, Panel (width/height/align). The backbone of UI and nested networks.",
       ["container", "panel", "ui", "network"], aliases=["container", "container comp"]),
    op("COMP", "Base COMP",
       "Base COMP is a generic organization/extension container with no rendering or UI of its own. Use it to group logic, store extensions, and create custom components. The default choice for a custom COMP.",
       ["base", "component", "organize", "extension"], aliases=["base", "base comp"]),
    op("COMP", "Geometry COMP",
       "Geometry COMP holds SOP geometry and a material for rendering. Set the 'Material' parameter to a MAT, and 'Geometry' to a SOP. Connect it to a Render TOP via a Camera COMP and Light COMP.",
       ["geometry", "render", "3d", "material"], aliases=["geo", "geometry comp"]),
    op("COMP", "Camera COMP",
       "Camera COMP defines a viewpoint for rendering. Parameters: Position, Look At, FOV, Near/Far. Reference its path in a Render TOP's Camera parameter.",
       ["camera", "render", "viewpoint", "fov"], aliases=["camera", "camera comp"]),
    op("COMP", "Light COMP",
       "Light COMP defines a light source for rendering (point, distant, cone, etc.). Parameters: Light Type, Color, Intensity, Cone. Reference it in a Render TOP's Light parameter.",
       ["light", "render", "illumination"], aliases=["light", "light comp"]),
    op("COMP", "Environment Light COMP",
       "Environment Light COMP lights a scene using an environment map (a TOP). Parameters: Env Map, Intensity. Use with PBR MAT for realistic reflections.",
       ["environment", "light", "pbr", "reflection"], aliases=["environment light comp"], min_version="2022.20000"),
    op("COMP", "Null COMP",
       "Null COMP is a pass-through COMP anchor (no transform change). Use it to expose a stable path and a clean input/output boundary in COMP networks.",
       ["null", "passthrough", "anchor"], aliases=["null comp"]),
    op("COMP", "Switch COMP",
       "Switch COMP selects one of several input COMPs by the Index parameter. Use to swap sub-networks programmatically.",
       ["switch", "select", "index"], aliases=["switch comp"]),
    op("COMP", "Select COMP",
       "Select COMP references another COMP (or its output) without copying. Parameters: COMP, Select. Use to pull in geometry/UI from elsewhere at a stable path.",
       ["select", "reference"], aliases=["select comp"]),
    op("COMP", "Window COMP",
       "Window COMP opens a separate OS window for a render/UI network. Parameters: Window Operator (the COMP to display), Borderless, Always On Top. Used for multi-screen/performance output.",
       ["window", "output", "display", "perform"], aliases=["window comp"]),
    op("COMP", "Perform COMP",
       "Perform COMP is the root of a performance UI; its contents are shown in Perform Mode. Parameters: Children, Background. Use for kiosks and shows.",
       ["perform", "ui", "show", "kiosk"], aliases=["perform comp"]),
    op("COMP", "Panel COMP",
       "Panel COMP is the base for all UI widgets; Button/Slider/Field COMPs build on it. Parameters: Panel (size, align), Value. Custom widgets subclass it.",
       ["panel", "ui", "widget", "component"], aliases=["panel comp"]),
    op("COMP", "Button COMP",
       "Button COMP is a clickable UI button. Parameters: Button State, Momentary/Toggle, Label. Read .panel.state or .par.value0 in scripts. Use for controls.",
       ["button", "ui", "click", "control"], aliases=["button comp"]),
    op("COMP", "Slider COMP",
       "Slider COMP is a draggable value slider (horizontal/vertical). Parameters: Slider Min/Max, Value. Export its value to drive parameters.",
       ["slider", "ui", "value", "control"], aliases=["slider comp"]),
    op("COMP", "Text COMP",
       "Text COMP displays editable/static text in the UI. Parameters: Text, Font, Align, Editable. Use for readouts and inputs.",
       ["text", "ui", "label", "display"], aliases=["text comp"]),
    op("COMP", "Reorder COMP",
       "Reorder COMP reorders/repeats the channels or inputs passing through it. Parameters: Reorder. Use to remap data streams.",
       ["reorder", "remap", "channels"], aliases=["reorder comp"]),
    op("COMP", "Keyboard In COMP",
       "Keyboard In COMP captures keyboard input for a UI panel. Parameters: Key, Scope. Use within Container/Perform COMPs for interaction.",
       ["keyboard", "in", "ui", "input"], aliases=["keyboard in comp"]),
    op("COMP", "Mouse In COMP",
       "Mouse In COMP reports mouse position within a panel. Parameters: u, v. Use for cursor-driven UI.",
       ["mouse", "in", "ui", "input"], aliases=["mouse in comp"]),
    op("COMP", "OSC In COMP",
       "OSC In COMP receives OSC messages into a component's parameters/callbacks. Parameters: Port. Use for network control of a COMP.",
       ["osc", "in", "network", "comp"], aliases=["osc in comp"]),
    op("COMP", "Web Render COMP",
       "Web Render COMP embeds a real web browser (Chromium) as a panel/texture. Parameters: URL, Reload. Use to show live web content inside TD.",
       ["web", "render", "browser", "chromium"], aliases=["web render comp"], min_version="2021.10000"),
    op("COMP", "Engine COMP",
       "Engine COMP runs a separate TouchDesigner process/file as a sub-engine for parallel processing/isolation. Parameters: File, Parameters. Advanced scaling tool.",
       ["engine", "process", "parallel"], aliases=["engine comp"]),
]

# ===========================================================================
# POP FAMILY (particles) -- version gated
# ===========================================================================
RECORDS += [
    op("POP", "POP Surface",
       "POP Surface is the primary POP that renders particle points/quads to the screen. Parameters: Render, Point Size, Color. It is the POP equivalent of a Render TOP for particles.",
       ["pop", "surface", "particle", "render"], aliases=["pop surface"], min_version="2023.10000"),
    op("POP", "POP Location",
       "POP Location generates particle positions (a point cloud) as the starting state of a particle system. Parameters: Generate (Grid/Sphere/Random), Count. Feed into a POP Solver.",
       ["pop", "location", "generate", "particles"], aliases=["pop location"], min_version="2023.10000"),
    op("POP", "POP Solver",
       "POP Solver simulates particles over time: integrates velocity, applies forces, handles life/collision. Parameters: Life, Forces, Collide. The simulation core of a POP network.",
       ["pop", "solver", "simulate", "particles"], aliases=["pop solver"], min_version="2023.10000"),
    op("POP", "POP Force",
       "POP Force applies forces (gravity, curl noise, attraction) to particles in a POP network. Parameters: Force, Noise, Turbulence. Connect into the POP Solver's force input.",
       ["pop", "force", "gravity", "noise", "particles"], aliases=["pop force"], min_version="2023.10000"),
    op("POP", "POP Trigger",
       "POP Trigger emits/scatters particles on events (e.g. when a CHOP crosses a threshold). Parameters: Emit Rate, On Event. Use for reactive bursts.",
       ["pop", "trigger", "emit", "particles"], aliases=["pop trigger"], min_version="2023.10000"),
    op("POP", "POP Stream Out",
       "POP Stream Out exports the current particle state (positions/attributes) to a SOP or CHOP for rendering/analysis. Parameters: Output. Bridges POPs back to classic pipelines.",
       ["pop", "stream", "out", "particles"], aliases=["pop stream out"], min_version="2023.10000"),
    op("POP", "POP Convert",
       "POP Convert converts SOP geometry into POP points (and vice versa), letting you mix particle and geometry workflows.",
       ["pop", "convert", "sop", "particles"], aliases=["pop convert"], min_version="2023.10000"),
    op("POP", "POPs family overview",
       "POPs are the Particle Operators family, introduced in the 2023.10000 build. They generate and simulate particles (POP Surface, POP Location, POP Solver, POP Force). Parameter identifiers and workflows differ from SOPs; do not assume SOP naming applies. Use a POP Render TOP or convert to SOPs for rendering.",
       ["particle", "pops", "2023", "overview"], aliases=["pops", "particle operators"], min_version="2023.10000"),
]

# ===========================================================================
# PYTHON API
# ===========================================================================
RECORDS += [
    py("OP_Class",
       "OP_Class is the base class for all operators in the TouchDesigner Python API. Key members: .par (parameters), .name, .path, .parent(), .children, .create(name, type) to make a child operator, .copy(ops) to duplicate, .destroy() to delete, .change() to force cook. tops/chops/sops/dats/comps properties give typed children lists. Use op('name') or parent().op('name') to fetch an operator.",
       ["python", "base", "api", "op"], aliases=["op", "op class", "op_class"]),
    py("COMP_Class",
       "COMP_Class is the Python class for Container/COMP operators. Members inherit OP_Class and add: .create(), .children (COMP children), .extensions, .panel (panel members for UI), .par for COMP parameters. Access via op('container1').",
       ["python", "comp", "component", "class"], aliases=["comp", "comp class", "comp_class"]),
    py("TOP_Class",
       "TOP_Class is the Python class for TOP operators. Members: .width, .height (cooked resolution), .aspect, .gpuMemory, .par for parameters. Access via op('top1'). Some TOPs (moviefileinTOP_Class) add clip-specific members.",
       ["python", "top", "class"], aliases=["top", "top class", "top_class"]),
    py("CHOP_Class",
       "CHOP_Class is the Python class for CHOP operators. Members: .numChannels, .numSamples, .sampleRate, .channel[index] / .chan(name), .vals, .par. Access channels with op('chop1')['channame'].",
       ["python", "chop", "class", "channel"], aliases=["chop", "chop class", "chop_class"]),
    py("SOP_Class",
       "SOP_Class is the Python class for SOP operators. Members: .numPoints, .numPrims, .points, .prims, .par. Geometry iteration uses .points and .prims with .P (position), .N (normal), .Cd (color) attributes.",
       ["python", "sop", "class", "geometry"], aliases=["sop", "sop class", "sop_class"]),
    py("DAT_Class",
       "DAT_Class is the Python class for DAT operators. Members: .text, .rows, .cols, .cell(row,col), .setCell(), .appendRow(), .clear(). Access cell value: op('table1')[0,'col'].value. Use .text for plain text.",
       ["python", "dat", "class", "table"], aliases=["dat", "dat class", "dat_class"]),
    py("Par_Class",
       "Par_Class represents a single parameter object. Members: .val/.value (current value), .name, .expr (expression string), .mode (constant/expression/binding/export), .enable, .pulse(). Set value: op('top1').par.rotatez = 0.5. Set expression: op('x').par.scale.expr = 'me.time.frame*0.01'.",
       ["python", "par", "parameter", "class"], aliases=["par", "par class", "parameter", "par_class"]),
    py("Cell_Class",
       "Cell_Class represents one cell of a Table DAT. Members: .val (string), .value (typed: number if numeric), .row, .col, .owner. Set: op('t')[0,0].val = 'hello'.",
       ["python", "cell", "dat", "table"], aliases=["cell", "cell class", "cell_class"]),
    py("Channel_Class",
       "Channel_Class represents one CHOP channel. Members: .val/.value (current sample), .name, .samples (all samples), .evalFrame(f), .min/.max. Access: op('chop1')['chan'].value.",
       ["python", "channel", "chop", "class"], aliases=["channel", "channel class", "channel_class"]),
    py("TDStoreTools / storage",
       "storage is a per-operator dictionary for persisting data across cooks and frames: op('x').store('key', value) and op('x').fetch('key'). It survives cook passes and is the recommended way to cache state (vs globals). Also see the `extension` mechanism on Base/COMP for object-oriented state.",
       ["python", "storage", "state", "persist"], aliases=["storage", "store", "tdstoretools", "fetch"]),
    py("ui module",
       "The `ui` module controls the TouchDesigner UI/runtime. Members: ui.message(text), ui.status, ui.panes, ui.viewers, ui.undo (the undo context manager), ui.performMode. Example: with ui.undo: op('x').par.value0 = 1  — wraps mutations in a single Ctrl+Z-able undo block.",
       ["python", "ui", "undo", "runtime"], aliases=["ui", "undo", "ui module"]),
    py("project module",
       "The `project` module is the global project object. Members: project.cook (the timeline/cook state), project.name, project.folder, project.save(), project.load(path). project.cook.play toggles playback; project.cook.rate is fps; project.cook.frame is the current frame.",
       ["python", "project", "cook", "timeline"], aliases=["project", "cook", "project module"]),
    py("me object",
       "The `me` object refers to the operator whose script is executing (the 'current' OP). Members: me.time (the time of the current cook), me.parent(), me.var. In a Text DAT script, `me` is that DAT. In parameter expressions, `me` is the operator owning the parameter.",
       ["python", "me", "current", "operator"], aliases=["me", "me object"]),
    py("op() and find() functions",
       "Global lookup functions: op('path') returns an operator by absolute/relative path; op.WToggle not needed. parent() returns the parent COMP; parent(2) the grandparent. root returns the root. findChildren() / findCell() search by name pattern and tags. Use op.TDResources for shared modules. For remote/path lookups use op('opname') and op('/project1/x').",
       ["python", "op", "find", "lookup", "path"], aliases=["op()", "find", "parent()", "root", "findchildren"]),
    py("App_Class",
       "App_Class is the application-level object accessible as `app`. Members: app.samples (sample rate), app.help, app.config, app.updateAll(). Represents the running TouchDesigner application instance.",
       ["python", "app", "application", "class"], aliases=["app", "app class", "app_class"]),
    py("timeClass (me.time)",
       "timeClass represents a cook's time context, accessed as me.time. Members: .frame (current frame), .seconds, .rate (fps), .play. Use in expressions/scripts to drive animation: me.time.frame.",
       ["python", "time", "frame", "seconds"], aliases=["timeclass", "me.time", "time class"]),
    py("dependencies / Par bindings",
       "Parameters can be linked with Bindings (TD 2022+): set a parameter's mode to 'Bind' and bind it to op('other').par.value. Dependencies (td.Par / tdu.Dependency) propagate updates reactively. Custom parameters are added via the 'Custom' parameter page of an operator (Edit Parameter Dialog).",
       ["python", "binding", "dependency", "custom parameter"], aliases=["binding", "dependency", "tdu.dependency", "custom parameter"], min_version="2022.20000"),
    py("tdu module",
       "The `tdu` module holds utilities: tdu.Dependency(val), tdu.FileTypes, tdu.splitString, tdu.radians()/tdu.degrees(), tdu.clamp(x,lo,hi), tdu.remap(). Useful helpers for Python scripting.",
       ["python", "tdu", "util", "helper"], aliases=["tdu", "tdu module"]),
    py("scriptDAT_Class",
       "scriptDAT_Class is the Python class for a Script DAT. Members: .text (script source), .run() (execute), .storage, .module (the executed module). Set Execute parameter for when it runs (On Start, On Frame Start, etc.).",
       ["python", "scriptdat", "class", "dat"], aliases=["scriptdat", "script dat class"]),
    py("moviefileinTOP_Class",
       "moviefileinTOP_Class is the Python class for a Movie File In TOP. Members: .par.file, .par.play, .par.speed, .width, .height (cooked resolution), .numFrames, .cueFrame. Access via op('moviein1'). Read .width/.height to get actual loaded video pixel size.",
       ["python", "moviefilein", "class", "top"], aliases=["moviefilein", "moviefilein class"]),
    py("Keyboard / Mouse panels (panel members)",
       "UI panel components expose a `panel` member: op('button1').panel.state (0/1), .u/.v (cursor in panel), .inside, .focus. Use these in Panel Execute DATs and Python to build responsive UI.",
       ["python", "panel", "ui", "state"], aliases=["panel member", "panel state"]),
    py("extension classes",
       "Custom COMP behavior is added via Extensions: a Text DAT with a Python class is attached in the COMP's 'Extension' parameter. Access via op('comp').MyExt or op('comp').extensions. Extensions hold persistent methods/state for reusable components.",
       ["python", "extension", "component", "class"], aliases=["extension", "extension class"]),
]

# ===========================================================================
# GLSL
# ===========================================================================
RECORDS += [
    glsl("GLSL fragment template",
         "GLSL TOP fragment shader template: uniform sampler2D sTD2DInputs[4]; out vec4 fragColor; void main() { vec2 uv = vUV.st; vec4 c = texture(sTD2DInputs[0], uv); fragColor = vec4(c.rgb * 1.2, c.a); }. Use uTD2DInfos[i].res for resolution. Wire a TOP into input 0. Output via 'fragColor'.",
         ["glsl", "shader", "fragment", "template"], aliases=["glsl fragment", "fragment template"]),
    glsl("GLSL vertex shader",
         "GLSL TOP vertex shader: use 'in vec3 P;' and 'out vec2 vUV;' to pass UVs to the fragment shader. The default pipeline provides P (position) and UV attributes. Modify gl_Position for vertex displacement. Declare 'uniform float uTime;' and set it from the GLSL TOP's Custom parameter page.",
         ["glsl", "vertex", "shader", "displace"], aliases=["glsl vertex", "vertex shader"]),
    glsl("GLSL multiple inputs",
         "A GLSL TOP can read up to 4 input TOPs: sTD2DInputs[0..3]. Sample each with texture(sTD2DInputs[i], uv). Blend them in the fragment shader. uTD2DInfos[i] holds per-input {res, clamp, depth}. Use for multi-texture effects.",
         ["glsl", "inputs", "multi", "sampler"], aliases=["glsl inputs", "multiple inputs"]),
    glsl("GLSL custom uniforms",
         "Custom uniforms in a GLSL TOP are declared in the shader (uniform float uAmount;) and bound via the GLSL TOP's 'Custom' parameter page: add 'uAmount' and set its value or export a CHOP channel to it. They update live without recompiling.",
         ["glsl", "uniform", "custom", "parameter"], aliases=["glsl uniform", "custom uniform"]),
    glsl("GLSL PBR / lighting",
         "For lit custom shaders use the PBR/Phong MAT's 'Lighting' via GLSL MAT, or compute lighting manually in a GLSL TOP. Phong-style: diffuse = max(dot(N, L), 0.0). A GLSL MAT lets a Geometry COMP use a fully custom shader with scene lighting and shadows.",
         ["glsl", "pbr", "phong", "lighting", "mat"], aliases=["glsl lighting", "glsl pbr"]),
    glsl("GLSL MAT",
         "GLSL MAT is a material that uses a custom vertex+fragment shader for rendering geometry (like a GLSL TOP but in the 3D pipeline). Wire into a Geometry COMP's Material parameter. Provides world/view/projection matrices and attribute varyings.",
         ["glsl", "mat", "material", "shader"], aliases=["glsl mat", "glsl material"]),
]

# ===========================================================================
# TUTORIALS / RECIPES
# ===========================================================================
RECORDS += [
    tut("CHOP Export to Parameters",
        "Export CHOP channels onto operator parameters so data drives visuals. Right-click a CHOP channel and choose Export, or in Python: op('chan1').exportOPar('null1', 'tx'). Exported parameters show a blue 'x' overlay. Clear with op('null1').unExport('tx'). Great for audio-reactive motion.",
        ["export", "chop", "parameter", "drive"], aliases=["export chop", "exportopar"]),
    tut("Connecting operators in Python",
        "Wire operators in Python: set op('null1').inputs[0] = op('noise1'), or use op('null1').inputConnectors[0].connect(op('noise1')). For outputs, op('null1').outputs[0].connect(op('out1')). Check valid connections with .validConnectors. Duplicate with .copy() before wiring to avoid breaking existing graphs.",
        ["wire", "connect", "python", "graph"], aliases=["wire", "connect operators", "inputconnectors"]),
    tut("Audio-reactive recipe",
        "Audio-reactive setup: Audio Device In CHOP -> Math CHOP (normalize) -> Filter CHOP. Export the filtered channel onto a TOP or COMP parameter with exportOPar, e.g. op('audi1').exportOPar('circle1', 'radius'). Use a Level TOP driven by the beat for a pulse effect.",
        ["audio", "reactive", "recipe", "beat"], aliases=["audio reactive", "audio recipe"]),
    tut("Feedback trails recipe",
        "Feedback trails: Noise TOP -> Level TOP (decay) -> Feedback TOP input0; Feedback TOP input1 gets the Level TOP output (the loop). Feedback TOP output -> another Level/Threshold for glow -> Out. Raise Level's Post slightly each frame to keep a fading trail.",
        ["feedback", "recipe", "trails", "loop"], aliases=["feedback recipe", "trails"]),
    tut("Render pipeline recipe",
        "Basic 3D render: Geometry COMP (with Material = Phong MAT, Geometry = a SOP) + Camera COMP + Light COMP -> Render TOP. Add a Null TOP after Render TOP as the stable output. Set the Render TOP's Camera and Light parameters to the COMP paths.",
        ["render", "pipeline", "recipe", "3d"], aliases=["render recipe", "render pipeline"]),
    tut("Instancing recipe",
        "GPU instancing: create a single SOP (e.g. Box SOP) in a Geo COMP, set the Geo's 'Instance' parameter to a CHOP or DAT providing per-instance transforms (tx,ty,tz,rx,ry,rz,sx,sy,sz). Thousands of copies render in one draw call. Drive the instance data from a CHOP to Table DAT or a SOP to CHOP.",
        ["instancing", "recipe", "gpu", "copies"], aliases=["instancing", "instance recipe"], min_version="2020.20000"),
    tut("OSC receive recipe",
        "Receive OSC: OSC In CHOP (set Port, e.g. 8000) -> channels appear per OSC address. Or OSC In DAT for raw messages. Map channels onto parameters via Export. Use a phone app (TouchOSC) sending to the machine's IP and that port.",
        ["osc", "receive", "recipe", "network"], aliases=["osc receive", "osc recipe"]),
    tut("Web API request recipe",
        "Call a REST API: Web Client DAT. Set op('web1').par.url and call op('web1').fetch(url, method='GET'). Handle the result in the onResponse callback, parse JSON with the stdlib json module, and write to a Table DAT. Use for live data feeds.",
        ["web", "api", "rest", "recipe", "json"], aliases=["web api", "rest recipe", "webclient recipe"]),
    tut("Particle render recipe (POPs)",
        "POPs particle system: POP Location (generate points) -> POP Force (gravity/noise) -> POP Solver (simulate) -> POP Surface (render). Add a Light COMP + Camera COMP + Render TOP (set to the POP Surface) to view. Tagged version 2023.10000+.",
        ["particle", "recipe", "pop", "render"], aliases=["particle recipe", "pop recipe"], min_version="2023.10000"),
    tut("Particle render recipe (GPU TOP)",
        "GPU particle system without POPs: Particle GPU TOP (Number, Life, Force) -> Point Sprite TOP / Billboard TOP -> Render TOP with a Camera. This runs entirely on the GPU and works on older builds.",
        ["particle", "gpu", "recipe", "top"], aliases=["gpu particle recipe"], min_version="2021.10000"),
    tut("Projection mapping basics",
        "Projection mapping: render content with a Render TOP using a Camera COMP placed at the projector; feed the Render TOP into a Projector COMP or directly to a Video Device Out TOP. Calibrate the camera's FO/position to the physical projector. Use Null TOPs as stable outputs.",
        ["projection", "mapping", "recipe", "projector"], aliases=["projection mapping", "projection recipe"]),
    tut("Data-driven UI recipe",
        "Build a data-driven UI: load a CSV with File In DAT / parse JSON from Web Client DAT into a Table DAT; use it to populate Button/Slider COMPs in a Container COMP. Read cell values with op('table1')[r,c].value in callbacks.",
        ["data", "ui", "recipe", "table"], aliases=["data driven ui", "ui recipe"]),
    tut("Undo-safe mutation pattern",
        "Wrap any Python mutation in an undo block so one Ctrl+Z reverts the whole batch: 'from td import *' not needed; use 'with ui.undo: op(\"x\").par.value0 = 1; op(\"y\").par.tx = 2'. This matches the safe-by-default bridge design and lets agents recover from mistakes.",
        ["undo", "safe", "mutation", "pattern"], aliases=["undo pattern", "undo safe"]),
    tut("Version-aware docs note",
        "TouchDesigner features are build-gated: POPs require >= 2023.10000; PBR MAT / Environment Light / Bindings >= 2022.20000; Web Render COMP >= 2021.10000. Always check min_version when applying a recipe to an older project to avoid referencing operators that don't exist there.",
        ["version", "build", "compat", "note"], aliases=["version note", "build compat"]),
    tut("Timeline control",
        "The TouchDesigner timeline is accessed via me.time or project.cook. Set playback with project.cook.play = True/False, project.cook.rate for fps, me.time.frame for current frame. Python class for time is timeClass. Range controls loop length. Use Timer CHOP or Run TOP for sequence control.",
        ["timeline", "frame", "fps", "play"], aliases=["timeline", "timeline control"]),
    tut("Custom parameter creation",
        "Add custom parameters to any operator via the parameter dialog (click the + on the 'Custom' page) or in Python via the Edit Parameter Dialog. Custom params appear on .par like built-ins and can be exported/bound. Use them to expose component controls cleanly.",
        ["custom", "parameter", "recipe", "ui"], aliases=["custom parameter", "custom par recipe"], min_version="2022.20000"),
    tut("CHOP to TOP visualization",
        "Visualize data: CHOP to TOP converts channels into an image (each channel a row). Pipe Audio Spectrum CHOP -> CHOP to TOP for a live spectrum display, or Trail CHOP -> CHOP to TOP for an oscilloscope. Then place the TOP on screen via a Container/Perform COMP.",
        ["chop to top", "visualize", "recipe", "spectrum"], aliases=["chop to top recipe", "visualize data"]),
    tut("Multi-instance / remote control",
        "Control a remote TouchDesigner: run a Touch Out TOP/CHOP to stream data, and a Touch In TOP/CHOP on the receiver. For command control, use a Web Server DAT or OSC In CHOP receiving from another instance. Single base URL + port routing handles multiple instances (see bridge design).",
        ["remote", "multi", "instance", "network"], aliases=["remote control", "multi instance"]),
    tut("Perform Mode / Windowing",
        "For shows: build the UI under a Perform COMP, then enter Perform Mode (F1/ctrl+F1) to display just that network fullscreen. Use a Window COMP for secondary displays and Video Device Out TOP for broadcast outputs. Set the Perform COMP as the perform target in Project Settings.",
        ["perform", "window", "show", "output"], aliases=["perform mode", "perform recipe"]),
]


def main():
    # Merge the merged MIT operator/Python corpus into the curated seeds so the
    # retriever benefits from 900+ operators + classes with version stamps.
    try:
        from td_mcp.kb.corpus import corpus_chunks
        RECORDS.extend(corpus_chunks())
    except Exception:  # noqa: BLE001
        pass

    # assign stable ids (records may already carry an explicit 'id')
    seen = {}
    out = []
    for r in RECORDS:
        if r.get("id"):
            cid = base = r["id"]
        else:
            base = re.sub(r"[^a-z0-9]+", "_", r["title"].lower()).strip("_")
            cid = base
        i = 1
        while cid in seen:
            i += 1
            cid = f"{base}_{i}"
        seen[cid] = True
        rec = {"id": cid}
        rec.update(r)
        out.append(rec)

    with open(OUT, "w", encoding="utf-8") as fh:
        for rec in out:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")

    from collections import Counter
    fam = Counter((r["family"] or r["category"]) for r in out)
    print(f"Wrote {len(out)} chunks -> {OUT}")
    for k, v in sorted(fam.items(), key=lambda x: -x[1]):
        print(f"  {k:10s} {v}")


if __name__ == "__main__":
    main()
