#!/usr/bin/env python3
"""One-shot TouchDesigner bridge bootstrap (bottobot style).

Paste this entire script into a Textport (or run `exec(open('bootstrap.py').read())`)
and it will:
  1. Create /td_mcp COMP with a WebServer DAT on TD_MCP_PORT (default 9980)
  2. Install the bridge logic into the WebServer DAT's onHTTPRequest callback
  3. Create an Execute DAT that mints + prints the auth token on start
  4. Set up protected paths, exec gate, and the full tool surface
  5. Print the connection URL and Bearer token for MCP client config

Requires TouchDesigner 2022+. No external dependencies.
"""

import os
import secrets
import textwrap

# ---------------------------------------------------------------------------
# Configuration (env-overridable)
# ---------------------------------------------------------------------------
TD_MCP_PORT = int(os.environ.get("TD_MCP_PORT", "9980"))
ALLOW_EXEC = os.environ.get("TD_MCP_ALLOW_EXEC", "1") != "0"
PROTECTED_PATHS = [p.strip() for p in os.environ.get("TD_MCP_PROTECTED_PATHS", "/sys,/ui,/local").split(",") if p.strip()]
AUTH_TOKEN = os.environ.get("TD_MCP_AUTH_TOKEN") or secrets.token_urlsafe(24)

# ---------------------------------------------------------------------------
# The bridge source code (kept in sync with td_mcp_bridge.py)
# ---------------------------------------------------------------------------
BRIDGE_SOURCE = r'''
"""td_mcp_bridge — auto-generated by bootstrap.py. Do not edit by hand."""

import base64
import hashlib
import hmac
import json
import os
import re
import secrets
import struct
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer

TD_MCP_PORT = {{TD_MCP_PORT}}
ALLOW_EXEC = {{ALLOW_EXEC}}
PROTECTED = {{PROTECTED_PATHS}}
AUTH_TOKEN = os.environ.get("TD_MCP_AUTH_TOKEN") or secrets.token_urlsafe(24)

RECOVERY_HINT_RULES = [
    (re.compile(r"cook|not cooked|invalid operation", re.I),
     "The operator could not cook or the operation was invalid.",
     "Check the operator exists and is cooked; verify parameter names with td_docs_parameter.",
     ["td_docs_parameter", "get_errors"]),
    (re.compile(r"no such|not found|unknown operator", re.I),
     "The path or operator type was not found.",
     "List nodes under the parent with list_nodes and confirm the type spelling.",
     ["list_nodes", "td_docs_family"]),
    (re.compile(r"parameter|par\\b", re.I),
     "A parameter name was invalid for this operator.",
     "Inspect the operator schema before setting values.",
     ["td_docs_parameter", "get_parameters"]),
    (re.compile(r"python|exec|syntax", re.I),
     "The Python snippet failed to execute.",
     "Fix the Python (check op() paths and imports) and retry.",
     ["td_docs_python", "get_errors"]),
    (re.compile(r"timeout|timed out", re.I),
     "The request timed out (likely a heavy cook).",
     "Retry with a smaller network or raise the client timeout.",
     ["get_errors"]),
]

def recovery_hints(message):
    for rx, cause, action, next_tools in RECOVERY_HINT_RULES:
        if rx.search(message or ""):
            return {"cause": cause, "action": action, "next_tools": next_tools[:2]}
    return None

def _resolve_path(path):
    if not path:
        return ""
    here_path = "/project1"
    this_path = ""
    try:
        import ui
        curr = ui.panes.current
        if curr and hasattr(curr, "owner") and curr.owner:
            here_path = curr.owner.path
            sel = curr.owner.selectedOps
            if sel:
                this_path = sel[0].path
        else:
            for p in ui.panes:
                if hasattr(p, "owner") and p.owner:
                    here_path = p.owner.path
                    sel = p.owner.selectedOps
                    if sel:
                        this_path = sel[0].path
                        break
                    break
    except Exception:
        pass
    path = path.replace("*here", here_path)
    if this_path:
        path = path.replace("*this", this_path)
    else:
        path = path.replace("*this", here_path)
    return path

def _op(path):
    resolved = _resolve_path(path)
    return op(resolved) if resolved else None

def _is_protected(path):
    if not PROTECTED:
        return False
    node = _op(path)
    for p in PROTECTED:
        if path == p or (node is not None and node.path.startswith(p + "/")):
            return True
    return False

def _family_of(node):
    try:
        return node.family
    except Exception:
        return ""

def _auto_position(parent_node, family):
    spacing = 220
    siblings = list(parent_node.children)
    row_y = None
    max_x = 0
    for c in siblings:
        if _family_of(c) == family:
            row_y = getattr(c, "nodeY", 0)
            max_x = max(max_x, c.nodeX)
    if row_y is None:
        row_y = (min((getattr(c, "nodeY", 0) for c in siblings), default=0) - spacing) if siblings else 0
        new_x = 0
    else:
        new_x = max_x + spacing
    return [new_x, row_y]

def _force_cook(node):
    try:
        node.cook(force=True, recurse=True)
    except Exception:
        try:
            node.cook(force=True)
        except Exception:
            pass

def _do_create(path, type, name=None, nodeX=None, nodeY=None):
    parent = _op(path) or parent()
    if parent is None:
        return {"ok": False, "error": f"parent not found: {path}"}
    node = parent.create(name or type.split()[-1], type)
    try:
        if nodeX is not None and nodeY is not None:
            node.nodeX, node.nodeY = nodeX, nodeY
        else:
            node.nodeX, node.nodeY = _auto_position(parent, getattr(node, "family", ""))
    except Exception:
        pass
    return {"ok": True, "path": node.path, "position": [getattr(node, "nodeX", 0), getattr(node, "nodeY", 0)]}

def _do_delete(path):
    if _is_protected(path):
        return {"ok": False, "error": f"path is protected from deletion: {path}"}
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    node.destroy()
    return {"ok": True}

def _do_set_parameters(path, params, detail="normal"):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    applied = {}
    for k, v in params.items():
        if k not in node.par:
            continue
        par = node.par[k]
        try:
            if isinstance(v, dict):
                if "expr" in v:
                    par.expr = v["expr"]
                if v.get("pulse"):
                    par.pulse()
                if "val" in v:
                    par.val = v["val"]
                applied[k] = v
            else:
                par.val = v
                applied[k] = v
        except Exception as e:
            applied[k] = f"error: {e}"
    if detail == "brief":
        return {"ok": True, "applied_count": len(applied)}
    return {"ok": True, "applied": applied}

def _do_get_parameters(path, detail="normal"):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    params = {p.name: p.val for p in node.par}
    if detail == "brief":
        return {"ok": True, "count": len(params)}
    if detail == "full":
        return {"ok": True, "params": params}
    return {"ok": True, "params": dict(list(params.items())[:40])}

def _do_get_errors(path):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    return {"ok": True, "errors": [str(e) for e in node.errors]}

def _do_execute_python(code):
    if not ALLOW_EXEC:
        return {"ok": False, "error": "execute_python is disabled (TD_MCP_ALLOW_EXEC=0)"}
    ns = {"op": op, "project": project, "me": me, "parent": parent}
    exec(code, ns)
    return {"ok": True, "result": repr(ns.get("result", None))}

def _do_list_nodes(path, detail="normal"):
    node = _op(path) or root()
    if node is None:
        return {"ok": False, "error": "not found"}
    kids = [{"name": c.name, "type": c.type, "path": c.path} for c in node.children]
    if detail == "brief":
        return {"ok": True, "count": len(kids)}
    return {"ok": True, "nodes": kids}

def _do_scan_network(path, depth=3):
    start_node = _op(path) or root()
    if start_node is None:
        return {"ok": False, "error": "not found"}
    scanned = []
    def traverse(node, current_depth):
        if node is None or current_depth > depth:
            return
        inputs = []
        try:
            inputs = [i.path for i in node.inputs if i is not None]
        except Exception:
            pass
        non_defaults = {}
        try:
            for p in node.par:
                if not p.isDefault:
                    non_defaults[p.name] = p.val
        except Exception:
            pass
        errors = []
        try:
            errors = [str(e) for e in node.errors]
        except Exception:
            pass
        scanned.append({
            "path": node.path, "name": node.name, "type": node.type,
            "inputs": inputs, "params": non_defaults, "errors": errors
        })
        try:
            for child in node.children:
                traverse(child, current_depth + 1)
        except Exception:
            pass
    traverse(start_node, 1)
    return {"ok": True, "nodes": scanned}

def _do_build_and_verify(path, op_type, name=None, params=None):
    r = _do_create(path, op_type, name)
    if not r.get("ok"):
        return r
    node_path = r["path"]
    if params:
        _do_set_parameters(node_path, params)
    errs = _do_get_errors(node_path)
    vp = _do_capture_viewport(node_path, "brief")
    return {"ok": True, "path": node_path, "errors": errs.get("errors", []), "viewport": vp.get("verdict")}

def _do_connect_nodes(from_path, to_path, from_output=0, to_input=0):
    src = _op(from_path)
    dst = _op(to_path)
    if src is None:
        return {"ok": False, "error": f"source not found: {from_path}"}
    if dst is None:
        return {"ok": False, "error": f"destination not found: {to_path}"}
    try:
        dst.inputConnectors[to_input].connect(src.outputConnectors[from_output])
        return {"ok": True, "connected": f"{src.path}[{from_output}] -> {dst.path}[{to_input}]"}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_rename_node(path, new_name):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    if _is_protected(path):
        return {"ok": False, "error": "path is protected"}
    old_name = node.name
    try:
        node.name = new_name
        return {"ok": True, "old_name": old_name, "new_name": node.name, "path": node.path}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_copy_node(path, new_parent, new_name=None):
    node = _op(path)
    parent_node = _op(new_parent)
    if node is None:
        return {"ok": False, "error": f"source not found: {path}"}
    if parent_node is None:
        return {"ok": False, "error": f"parent not found: {new_parent}"}
    try:
        pasted = parent_node.copy(node, name=new_name)
        return {"ok": True, "path": pasted.path}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_auto_layout(path, direction="left-right", spacing_x=200, spacing_y=200):
    node = _op(path) or root()
    if node is None:
        return {"ok": False, "error": "not found"}
    try:
        children = list(node.children)
        for idx, child in enumerate(children):
            if direction == "left-right":
                child.nodeX = idx * spacing_x
                child.nodeY = 0
            else:
                child.nodeX = 0
                child.nodeY = -(idx * spacing_y)
        return {"ok": True, "arranged": len(children)}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_get_node(path):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    non_defaults = {}
    try:
        for p in node.par:
            if not p.isDefault:
                non_defaults[p.name] = p.val
    except Exception:
        pass
    inputs = []
    try:
        inputs = [c.outputOP.path for c in node.inputConnectors if c and c.outputOP]
    except Exception:
        pass
    outputs = []
    try:
        outputs = [c.inputOP.path for oc in node.outputConnectors for c in oc.connections if c and c.inputOP]
    except Exception:
        pass
    errors = []
    try:
        errors = [str(e) for e in node.errors]
    except Exception:
        pass
    return {
        "ok": True, "name": node.name, "type": node.type, "path": node.path,
        "inputs": inputs, "outputs": outputs, "params": non_defaults,
        "errors": errors, "position": [getattr(node, 'nodeX', 0), getattr(node, 'nodeY', 0)],
    }

def _do_set_node_color(path, r, g, b):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    try:
        node.color = (r, g, b)
        return {"ok": True, "color": [r, g, b]}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_set_node_comment(path, comment=None, tags=None):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    try:
        if comment is not None:
            node.comment = comment
        if tags is not None:
            node.tags = tags if isinstance(tags, list) else [t.strip() for t in str(tags).split(",") if t.strip()]
        return {"ok": True, "comment": getattr(node, "comment", ""), "tags": list(getattr(node, "tags", []) or [])}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_map_network(path, depth=2):
    start_node = _op(path) or root()
    if start_node is None:
        return {"ok": False, "error": "not found"}
    nodes = []
    edges = []
    seen = set()
    def traverse(node, d):
        if node is None or d > depth or node.path in seen:
            return
        seen.add(node.path)
        ndef = (f'  "{{node.path}}" [label="{node.name}\\n{node.type}", '
                f'pos="{getattr(node, "nodeX", 0)},{getattr(node, "nodeY", 0)}!"];')
        nodes.append(ndef)
        try:
            for out_idx, out_op in enumerate(getattr(node, "outputs", []) or []):
                targets = []
                try:
                    targets = [c.inputOP.path for oc in node.outputConnectors[out_idx].connections
                               if oc and oc.inputOP]
                except Exception:
                    pass
                for t in targets:
                    edges.append(f'  "{{node.path}}" -> "{{t}}";')
        except Exception:
            pass
        try:
            for child in node.children:
                traverse(child, d + 1)
        except Exception:
            pass
    traverse(start_node, 1)
    dot = "digraph td_network {\n  rankdir=LR;\n  node [shape=box, style=rounded];\n"
    dot += "\n".join(nodes) + "\n" + "\n".join(edges) + "\n}\n"
    return {"ok": True, "format": "dot", "dot": dot, "node_count": len(nodes)}

def _do_disconnect_nodes(from_path, to_path, to_input=0):
    src = _op(from_path)
    dst = _op(to_path)
    if dst is None:
        return {"ok": False, "error": f"destination not found: {to_path}"}
    try:
        target = src.path if src else None
        for c in list(dst.inputConnectors[to_input].connections):
            if c.outputOP and c.outputOP.path == target:
                c.disconnect()
        return {"ok": True, "disconnected": f"{from_path} -x-> {to_path}[{to_input}]"}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_get_connections(path):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    ins = []
    try:
        for i, ic in enumerate(node.inputConnectors):
            for c in ic.connections:
                if c and c.outputOP:
                    ins.append({"input": i, "from": c.outputOP.path})
    except Exception:
        pass
    outs = []
    try:
        for i, oc in enumerate(node.outputConnectors):
            for c in oc.connections:
                if c and c.inputOP:
                    outs.append({"output": i, "to": c.inputOP.path})
    except Exception:
        pass
    return {"ok": True, "inputs": ins, "outputs": outs}

def _do_exec_node_method(path, method, args=None):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    try:
        fn = getattr(node, method)
        res = fn(*(args or []))
        return {"ok": True, "result": repr(res)}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_snapshot_network(path):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    import tempfile, time
    out = os.path.join(tempfile.gettempdir(), f"td_mcp_snap_{node.name}_{int(time.time())}.tox")
    try:
        node.save(out)
        return {"ok": True, "snapshot": out}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_restore_network(snapshot, target_parent="*here"):
    parent = _op(target_parent) or parent()
    if parent is None:
        return {"ok": False, "error": "parent not found"}
    if not snapshot or not os.path.exists(snapshot):
        return {"ok": False, "error": f"snapshot not found: {snapshot}"}
    try:
        loaded = parent.loadTox(snapshot)
        return {"ok": True, "path": loaded.path}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_get_performance(path):
    node = _op(path) or root()
    if node is None:
        return {"ok": False, "error": "not found"}
    rows = []
    try:
        for c in node.children:
            rows.append({"path": c.path, "type": c.type,
                         "cook_time": round(float(getattr(c, "cookTime", 0) or 0), 4),
                         "cpu": round(float(getattr(c, "cpuCookTime", 0) or 0), 4),
                         "gpu": round(float(getattr(c, "gpuCookTime", 0) or 0), 4)})
    except Exception:
        pass
    rows.sort(key=lambda r: r["cook_time"], reverse=True)
    return {"ok": True, "fps": project.cook.rate, "cooks": rows, "hotspots": rows[:5]}

def _do_validate_network(path, depth=2):
    start = _op(path) or root()
    if start is None:
        return {"ok": False, "error": "not found"}
    issues = []
    positions = {}
    def traverse(node, d):
        if node is None or d > depth:
            return
        nx, ny = getattr(node, "nodeX", 0), getattr(node, "nodeY", 0)
        if nx == 0 and ny == 0:
            issues.append({"severity": "warn", "path": node.path,
                           "issue": "node sits at the origin (0,0) - likely unplaced"})
        key = (nx, ny)
        if key in positions:
            issues.append({"severity": "warn", "path": node.path,
                           "issue": f"overlaps {positions[key]} at {key}"})
        else:
            positions[key] = node.path
        try:
            for e in node.errors:
                issues.append({"severity": "error", "path": node.path, "issue": f"cook error: {e}"})
        except Exception:
            pass
        try:
            for child in node.children:
                traverse(child, d + 1)
        except Exception:
            pass
    traverse(start, 1)
    sev = {"error": 0, "warn": 0}
    for it in issues:
        sev[it["severity"]] = sev.get(it["severity"], 0) + 1
    return {"ok": True, "issue_count": len(issues), "by_severity": sev, "issues": issues}

_NODE_FLAGS = ("bypass", "viewer", "excludeFromCook", "allowCooking",
               "forceCooking", "cloneImmune", "pickable")

def _do_set_flags(path, flags=None):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    flags = flags or {}
    applied = {}
    for k, v in flags.items():
        if k in _NODE_FLAGS:
            try:
                setattr(node, k, bool(v))
                applied[k] = bool(v)
            except Exception as e:
                applied[k] = f"error: {e}"
    return {"ok": True, "applied": applied}

def _do_find_nodes(path, query=None, op_type=None, depth=4):
    start = _op(path) or root()
    if start is None:
        return {"ok": False, "error": "not found"}
    q = (query or "").lower()
    matches = []
    def traverse(node, d):
        if node is None or d > depth:
            return
        if q and q in node.name.lower():
            matches.append({"path": node.path, "name": node.name, "type": node.type})
        if op_type and op_type.lower() in node.type.lower():
            matches.append({"path": node.path, "name": node.name, "type": node.type})
        try:
            for child in node.children:
                traverse(child, d + 1)
        except Exception:
            pass
    traverse(start, 1)
    return {"ok": True, "count": len(matches), "matches": matches}

def _do_set_node_position(path, x, y):
    node = _op(path)
    if node is None:
        return {"ok": False, "error": "not found"}
    try:
        node.nodeX, node.nodeY = x, y
        return {"ok": True, "path": node.path, "position": [node.nodeX, node.nodeY]}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_timeline(action, value=None):
    tl = project.cook
    try:
        if action in ("play", "pause", "toggle"):
            if action == "play":
                tl.play = True
            elif action == "pause":
                tl.play = False
            else:
                tl.play = not tl.play
            return {"ok": True, "play": tl.play}
        if action == "frame":
            tl.time = float(value)
            return {"ok": True, "time": tl.time}
        if action == "seek":
            tl.time = max(1.0, tl.time + float(value))
            return {"ok": True, "time": tl.time}
        if action == "rate":
            tl.rate = float(value)
            return {"ok": True, "rate": tl.rate}
        return {"ok": False, "error": f"unknown timeline action: {action}"}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _do_export_recipe(path, depth=3):
    start = _op(path) or root()
    if start is None:
        return {"ok": False, "error": "not found"}
    nodes = []
    def traverse(node, d):
        if node is None or d > depth:
            return
        params = {}
        try:
            for p in node.par:
                if not p.isDefault:
                    params[p.name] = p.val
        except Exception:
            pass
        inputs = {}
        try:
            for i, ic in enumerate(node.inputConnectors):
                for c in ic.connections:
                    if c and c.outputOP:
                        inputs[str(i)] = c.outputOP.path
        except Exception:
            pass
        nodes.append({
            "name": node.name, "type": node.type,
            "position": [getattr(node, "nodeX", 0), getattr(node, "nodeY", 0)],
            "params": params, "inputs": inputs,
            "children": [c.name for c in node.children],
        })
        try:
            for child in node.children:
                traverse(child, d + 1)
        except Exception:
            pass
    traverse(start, 1)
    return {"ok": True, "root": start.path, "node_count": len(nodes), "recipe": nodes}

def _do_import_recipe(recipe, target_parent="*here"):
    parent = _op(target_parent) or parent()
    if parent is None:
        return {"ok": False, "error": "parent not found"}
    if isinstance(recipe, str):
        try:
            recipe = json.loads(recipe)
        except Exception as e:
            return {"ok": False, "error": f"bad recipe json: {e}"}
    nodes = recipe if isinstance(recipe, list) else recipe.get("recipe", [])
    if not isinstance(nodes, list):
        return {"ok": False, "error": "recipe must be a list of node specs"}
    created = {}
    for spec in nodes:
        name = spec.get("name")
        op_type = spec.get("type")
        if not name or not op_type:
            continue
        node = parent.create(name, op_type)
        created[name] = node
        try:
            node.nodeX, node.nodeY = spec.get("position", [0, 0])
        except Exception:
            pass
        for k, v in spec.get("params", {}).items():
            if k in node.par:
                try:
                    node.par[k].val = v
                except Exception:
                    pass
    wired = 0
    for spec in nodes:
        dst = created.get(spec.get("name"))
        if dst is None:
            continue
        for idx, src_name in spec.get("inputs", {}).items():
            src = created.get(src_name)
            if src is None:
                continue
            try:
                dst.inputConnectors[int(idx)].connect(src.outputConnectors[0])
                wired += 1
            except Exception:
                pass
    return {"ok": True, "created": len(created), "wired": wired,
            "paths": [n.path for n in created.values()]}

def _do_project_info():
    return {"ok": True, "td_build": app.version, "fps": project.cook.rate, "file": project.name}

# ---------------------------------------------------------------------------
# HTTP / WebSocket server
# ---------------------------------------------------------------------------
_ws_clients = set()
_ws_lock = threading.Lock()

def _ws_push(event):
    if not _ws_clients:
        return
    frame = _ws_make_frame(json.dumps({"type": "event", "event": event}))
    drop = []
    with _ws_lock:
        for client in list(_ws_clients):
            try:
                client.wfile.write(frame)
                client.wfile.flush()
            except Exception:
                drop.append(client)
        for client in drop:
            _ws_clients.discard(client)

def _ws_handshake_key(key):
    return base64.b64encode(hashlib.sha1((key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11").encode("utf-8")).digest()).decode("utf-8")

def _ws_make_frame(payload, opcode=0x1):
    if isinstance(payload, str):
        payload = payload.encode("utf-8")
    length = len(payload)
    if length < 126:
        header = struct.pack(">BB", 0x80 | opcode, length)
    elif length < 65536:
        header = struct.pack(">BBH", 0x80 | opcode, 126, length)
    else:
        header = struct.pack(">BBQ", 0x80 | opcode, 127, length)
    return header + payload

def _ws_read_frame(rfile):
    header = rfile.read(2)
    if len(header) < 2:
        return None, None
    b0, b1 = header
    opcode = b0 & 0x0F
    masked = (b1 & 0x80) != 0
    length = b1 & 0x7F
    if length == 126:
        length = struct.unpack(">H", rfile.read(2))[0]
    elif length == 127:
        length = struct.unpack(">Q", rfile.read(8))[0]
    mask = rfile.read(4) if masked else None
    data = rfile.read(length)
    if masked:
        data = bytes(b ^ mask[i % 4] for i, b in enumerate(data))
    return opcode, data

_DISPATCH = {
    "create_node": lambda a: _do_create(a.get("path"), a.get("type"), a.get("name"), a.get("nodeX"), a.get("nodeY")),
    "delete_node": lambda a: _do_delete(a.get("path")),
    "set_parameters": lambda a: _do_set_parameters(a.get("path"), a.get("params", {}), a.get("detail", "normal")),
    "get_parameters": lambda a: _do_get_parameters(a.get("path"), a.get("detail", "normal")),
    "get_errors": lambda a: _do_get_errors(a.get("path")),
    "execute_python": lambda a: _do_execute_python(a.get("code")),
    "list_nodes": lambda a: _do_list_nodes(a.get("path"), a.get("detail", "normal")),
    "project_info": lambda a: _do_project_info(),
    "capture_viewport": lambda a: _do_capture_viewport(a.get("path"), a.get("detail", "normal")),
    "get_resource": lambda a: _do_get_resource(a.get("uri")),
    "describe_td_tools": lambda a: _do_describe(),
    "batch": lambda a: _do_batch(a.get("ops", [])),
    "read_chop": lambda a: _do_read_chop(a.get("path"), a.get("channel"), a.get("samples", 10)),
    "read_top": lambda a: _do_read_top(a.get("path"), a.get("detail", "brief")),
    "read_dat": lambda a: _do_read_dat(a.get("path"), a.get("rows", 10)),
    "scan_network": lambda a: _do_scan_network(a.get("path"), a.get("depth", 3)),
    "build_and_verify": lambda a: _do_build_and_verify(a.get("path"), a.get("op_type"), a.get("name"), a.get("params")),
    "connect_nodes": lambda a: _do_connect_nodes(a.get("from_path"), a.get("to_path"), a.get("from_output", 0), a.get("to_input", 0)),
    "rename_node": lambda a: _do_rename_node(a.get("path"), a.get("new_name")),
    "copy_node": lambda a: _do_copy_node(a.get("path"), a.get("new_parent"), a.get("new_name")),
    "auto_layout": lambda a: _do_auto_layout(a.get("path"), a.get("direction", "left-right"), a.get("spacing_x", 200), a.get("spacing_y", 200)),
    "get_node": lambda a: _do_get_node(a.get("path")),
    "set_node_color": lambda a: _do_set_node_color(a.get("path"), a.get("r", 0), a.get("g", 0), a.get("b", 0)),
    "set_node_comment": lambda a: _do_set_node_comment(a.get("path"), a.get("comment"), a.get("tags")),
    "map_network": lambda a: _do_map_network(a.get("path"), a.get("depth", 2)),
    "disconnect_nodes": lambda a: _do_disconnect_nodes(a.get("from_path"), a.get("to_path"), a.get("to_input", 0)),
    "get_connections": lambda a: _do_get_connections(a.get("path")),
    "exec_node_method": lambda a: _do_exec_node_method(a.get("path"), a.get("method"), a.get("args")),
    "snapshot_network": lambda a: _do_snapshot_network(a.get("path")),
    "restore_network": lambda a: _do_restore_network(a.get("snapshot"), a.get("target_parent", "*here")),
    "get_performance": lambda a: _do_get_performance(a.get("path")),
    "validate_network": lambda a: _do_validate_network(a.get("path"), a.get("depth", 2)),
    "set_flags": lambda a: _do_set_flags(a.get("path"), a.get("flags")),
    "find_nodes": lambda a: _do_find_nodes(a.get("path"), a.get("query"), a.get("type"), a.get("depth", 4)),
    "set_node_position": lambda a: _do_set_node_position(a.get("path"), a.get("x", 0), a.get("y", 0)),
    "timeline": lambda a: _do_timeline(a.get("action"), a.get("value")),
    "export_recipe": lambda a: _do_export_recipe(a.get("path"), a.get("depth", 3)),
    "import_recipe": lambda a: _do_import_recipe(a.get("recipe"), a.get("target_parent", "*here")),
    "save_tox": lambda a: _do_save_tox(a.get("path"), a.get("file_path")),
}

def _do_describe():
    return {"ok": True, "auth_required": True, "allow_exec": ALLOW_EXEC,
            "protected_paths": PROTECTED, "tools": sorted(_DISPATCH.keys())}

def _do_batch(ops):
    results = []
    for call in ops:
        tool = call.get("tool")
        fn = _DISPATCH.get(tool)
        if fn is None:
            results.append({"tool": tool, "ok": False, "error": "unknown tool"})
            continue
        try:
            with ui.undo:
                results.append({"tool": tool, "result": fn(call.get("args", {}))})
        except Exception as e:
            results.append({"tool": tool, "ok": False, "error": str(e),
                          "recovery_hints": recovery_hints(str(e))})
    return {"ok": True, "batch": results}

def _do_get_resource(uri):
    m = re.match(r"td://([^/]+)/(.*)", uri or "")
    if not m:
        return {"ok": False, "error": "bad td:// uri"}
    kind, rest = m.group(1), m.group(2)
    if kind == "project":
        return _do_project_info()
    if kind == "errors":
        return _do_get_errors(rest)
    if kind == "chop":
        node = _op(rest)
        if node is None:
            return {"ok": False, "error": "not found"}
        return {"ok": True, "channels": [c.name for c in node.chans]}
    if kind == "node":
        node = _op(rest)
        if node is None:
            return {"ok": False, "error": "not found"}
        return {"ok": True, "name": node.name, "type": node.type,
                "path": node.path, "children": len(node.children)}
    return {"ok": False, "error": f"unknown resource: {kind}"}

def _wrap(result):
    if isinstance(result, dict) and result.get("ok") is False and "recovery_hints" not in result:
        hints = recovery_hints(result.get("error", ""))
        if hints:
            result["recovery_hints"] = hints
    return result

class MCPHandler(BaseHTTPRequestHandler):
    def _send(self, data, status=200):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode("utf-8"))

    def _auth_ok(self):
        supplied = self.headers.get("Authorization", "")
        expected = f"Bearer {AUTH_TOKEN}"
        return hmac.compare_digest(supplied, expected)

    def _handle_websocket(self):
        key = self.headers.get("Sec-WebSocket-Key", "")
        accept = _ws_handshake_key(key)
        self.send_response(101)
        self.send_header("Upgrade", "websocket")
        self.send_header("Connection", "Upgrade")
        self.send_header("Sec-WebSocket-Accept", accept)
        self.end_headers()
        self.wfile.flush()
        with _ws_lock:
            _ws_clients.add(self)
        try:
            opcode, raw = _ws_read_frame(self.rfile)
            if opcode is None:
                return
            try:
                auth_msg = json.loads(raw.decode("utf-8"))
            except Exception:
                auth_msg = {}
            if auth_msg.get("type") == "auth":
                if not hmac.compare_digest(str(auth_msg.get("token", "")), AUTH_TOKEN):
                    self.wfile.write(_ws_make_frame(json.dumps({"ok": False, "error": "unauthorized"})))
                    self.wfile.flush()
                    return
                self.wfile.write(_ws_make_frame(json.dumps({"ok": True, "status": "authenticated"})))
                self.wfile.flush()
            else:
                self.wfile.write(_ws_make_frame(json.dumps({"ok": False, "error": "auth required"})))
                self.wfile.flush()
                return
            while True:
                opcode, raw = _ws_read_frame(self.rfile)
                if opcode is None or opcode == 0x8:
                    break
                try:
                    req = json.loads(raw.decode("utf-8"))
                except Exception:
                    continue
                msg_id = req.get("id")
                tool = req.get("tool")
                fn = _DISPATCH.get(tool)
                if fn is None:
                    resp = {"id": msg_id, "ok": False, "error": f"unknown tool: {tool}"}
                else:
                    try:
                        with ui.undo:
                            result = _wrap(fn(req.get("args", {})))
                        ok = result.get("ok") if isinstance(result, dict) else True
                        _ws_push({"tool": tool, "ok": ok})
                        resp = {"id": msg_id, "ok": True, "result": result}
                    except Exception as e:
                        _ws_push({"tool": tool, "ok": False, "error": str(e)})
                        resp = {"id": msg_id, "ok": False, "error": str(e)}
                self.wfile.write(_ws_make_frame(json.dumps(resp)))
                self.wfile.flush()
        except Exception:
            pass
        finally:
            with _ws_lock:
                _ws_clients.discard(self)

    def do_GET(self):
        if self.headers.get("Upgrade", "").lower() == "websocket":
            self._handle_websocket()
            return
        if self.path in ("/", "/ui", "/chat"):
            self._send({"ok": True, "status": "running", "port": TD_MCP_PORT, "auth": True, "allow_exec": ALLOW_EXEC})
            return
        if self.path == "/api/status":
            self._send({"ok": True, "status": "running", "port": TD_MCP_PORT, "auth": True, "allow_exec": ALLOW_EXEC})
        elif self.path.startswith("/api/resource?"):
            m = re.search(r"uri=([^&]+)", self.path)
            uri = m.group(1).replace("%3A", ":").replace("%2F", "/") if m else ""
            from urllib.parse import unquote
            uri = unquote(uri)
            self._send(_wrap(_do_get_resource(uri)))
        else:
            self._send({"ok": False, "error": "not found"}, 404)

    def do_POST(self):
        if self.path != "/mcp":
            self._send({"ok": False, "error": "not found"}, 404)
            return
        if not self._auth_ok():
            self._send({"ok": False, "error": "unauthorized"}, 401)
            return
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            req = json.loads(raw.decode("utf-8") or "{}")
        except Exception:
            self._send({"ok": False, "error": "bad json"}, 400)
            return
        tool = req.get("tool")
        fn = _DISPATCH.get(tool)
        if fn is None:
            self._send({"ok": False, "error": f"unknown tool: {tool}"})
            return
        try:
            with ui.undo:
                result = _wrap(fn(req.get("args", {})))
            ok = result.get("ok") if isinstance(result, dict) else True
            _ws_push({"tool": tool, "ok": ok})
            self._send(result or {"ok": True})
        except Exception as e:
            _ws_push({"tool": tool, "ok": False, "error": str(e)})
            self._send(_wrap({"ok": False, "error": str(e)}), 500)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "http://127.0.0.1")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
        self.end_headers()

    def log_message(self, *args):
        pass

def start():
    global _server, _server_thread
    _server = HTTPServer(("127.0.0.1", TD_MCP_PORT), MCPHandler)
    _server_thread = threading.Thread(target=_server.serve_forever, daemon=True)
    _server_thread.start()
    print(f"td-mcp bridge listening on http://127.0.0.1:{TD_MCP_PORT}")
    print(f"Auth token: {AUTH_TOKEN}")
    print(f"WebSocket: ws://127.0.0.1:{TD_MCP_PORT} (send {{\"type\":\"auth\",\"token\":\"...\"}} first)")

def stop():
    global _server
    if _server:
        _server.shutdown()
        _server = None
'''

def main():
    print("=" * 60)
    print("td-mcp Bridge Bootstrap")
    print("=" * 60)

    # 1. Create /td_mcp COMP if missing
    td_mcp = op("/td_mcp")
    if td_mcp is None:
        td_mcp = project.root.create("td_mcp", "containerCOMP")
        print("Created /td_mcp COMP")

    # 2. Create WebServer DAT
    ws = td_mcp.op("webserver")
    if ws is None:
        ws = td_mcp.create("webserver", "webserverDAT")
        ws.par.port = TD_MCP_PORT
        ws.par.rootpath = "/td_mcp"
        print(f"Created WebServer DAT on port {TD_MCP_PORT}")

    # 3. Install bridge source into a Text DAT
    source = BRIDGE_SOURCE.replace("{{TD_MCP_PORT}}", str(TD_MCP_PORT)) \
                         .replace("{{ALLOW_EXEC}}", str(ALLOW_EXEC)) \
                         .replace("{{PROTECTED_PATHS}}", repr(PROTECTED_PATHS))
    src_dat = td_mcp.op("bridge_source")
    if src_dat is None:
        src_dat = td_mcp.create("bridge_source", "textDAT")
    src_dat.text = source
    print("Installed bridge source")

    # 4. Configure WebServer DAT to use our handler class
    ws.par.onhttpobject = "op('bridge_source')"
    ws.par.onhttprequest = "op('bridge_source').module.MCPHandler"
    ws.par.callbackson = True

    # 5. Create Execute DAT that mints token on start
    exec_dat = td_mcp.op("mint_token")
    if exec_dat is None:
        exec_dat = td_mcp.create("mint_token", "executeDAT")
    exec_dat.text = f'''
import os
os.environ["TD_MCP_AUTH_TOKEN"] = os.environ.get("TD_MCP_AUTH_TOKEN") or "{AUTH_TOKEN}"
os.environ["TD_MCP_ALLOW_EXEC"] = "1" if {ALLOW_EXEC} else "0"
os.environ["TD_MCP_PROTECTED_PATHS"] = {repr(PROTECTED_PATHS)}
print("td-mcp bridge token:", os.environ["TD_MCP_AUTH_TOKEN"])
print("Bridge ready at http://127.0.0.1:{TD_MCP_PORT}/mcp")
'''
    exec_dat.par.startup = True
    exec_dat.par.onexecute = "mint_token"

    # 6. Create Callbacks DAT to start the server
    cb = td_mcp.op("callbacks")
    if cb is None:
        cb = td_mcp.create("callbacks", "callbacksDAT")
    cb.text = f'''
def onStart():
    import threading
    from http.server import HTTPServer
    from op("bridge_source").module import MCPHandler, TD_MCP_PORT
    server = HTTPServer(("127.0.0.1", TD_MCP_PORT), MCPHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    op("td_mcp").server = server
    print("td-mcp bridge started on http://127.0.0.1:{TD_MCP_PORT}")
    print("Auth token:", os.environ.get("TD_MCP_AUTH_TOKEN"))

def onStop():
    server = getattr(op("td_mcp"), "server", None)
    if server:
        server.shutdown()
        print("td-mcp bridge stopped")
'''
    print("Created callbacks")

    print("\n" + "=" * 60)
    print("BOOTSTRAP COMPLETE")
    print("=" * 60)
    print(f"Bridge COMP: /td_mcp")
    print(f"WebServer DAT: /td_mcp/webserver (port {TD_MCP_PORT})")
    print(f"Auth token: {AUTH_TOKEN}")
    print(f"\nTo start the bridge, run in Textport:")
    print(f"  op('/td_mcp/callbacks').module.onStart()")
    print(f"\nMCP client config (Claude Desktop / Cursor):")
    print(f'  {{"td-mcp-live": {{"url": "http://127.0.0.1:{TD_MCP_PORT}/mcp", "headers": {{"Authorization": "Bearer {AUTH_TOKEN}"}}}}}}')
    print("=" * 60)