#!/usr/bin/env python3
"""Generate a clean, code-free summary of the td-mcp repository.

This is the *repomix-style* summary generator for ``td-mcp``. Unlike a raw
``repomix`` pack (which always inlines every file's source), this script
produces a **single, code-free** ``SUMMARY.md`` that contains only:

  * a general project overview,
  * the high-level architecture,
  * the directory tree,
  * a 1–2 line explanation of *every* tracked file (sourced from each file's own
    module docstring / first heading — never from its code).

No source code is copied into the output. This is the one artifact the project
ships for LLM / README context: a list of files, the architecture, the tree, and
short per-file descriptions, and nothing else.

Run:
    uv run python scripts/generate_summary.py
    python scripts/generate_summary.py            # works with plain python3 too

Optional: if you *do* want a full source pack (all code inlined), install
``repomix`` and run it manually with ``repomix.config.json``. That path is NOT
taken by default — ``generate_summary.py`` writes exactly one file.

Optional: if the ``repomix`` CLI is installed (``npm i -g repomix`` or
``npx repomix``), pass ``--repomix`` to ALSO emit a full repomix pack using
``repomix.config.json``. The curated ``SUMMARY.md`` is always written.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
ROOT = Path(__file__).resolve().parent.parent

# Directories / files that are build artifacts or environment, never source.
EXCLUDE_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
    "dist",
    "build",
    ".eggs",
    ".egg-info",
}

# Hand-written descriptions for files whose name alone is unclear.
FILE_OVERRIDES = {
    "td_mcp/__init__.py": "Package root re-exporting the public retrieval API (`Retriever`, `build_retriever`, `tokenize`).",
    "td_mcp/rag/__init__.py": "RAG subpackage re-export of the retrieval API.",
    "td_mcp/kb/__init__.py": "KB subpackage marker (runtime corpus access lives in `corpus.py`).",
    "td_mcp/tools/__init__.py": "Tools subpackage marker (risk / recovery / logs / layout helpers).",
    "td_mcp.egg-info/SOURCES.txt": "Build artifact listing packaged sources (generated by setuptools).",
    "setup_env.ps1": "One-shot PowerShell bootstrap that pins Python 3.11.10 (TD's interpreter) via uv and installs td-mcp.",
    "repomix.config.json": "Repomix configuration (include/exclude + output style) for emitting a full source pack.",
    ".python-version": "Pins the interpreter to 3.11.10 so the venv matches TouchDesigner's Python.",
}

# File globs we want to SUMMARISE (everything else is skipped).
INCLUDE_GLOBS = ("*.py", "*.md", "*.toml", "*.ps1", "*.html", "*.json", "*.cfg", "*.ini")

# Generated / large data files we list by name but never read for description.
DATA_FILES = {
    "td_mcp/kb/chunks.jsonl",
    "td_mcp/kb/embeddings.jsonl",
    "uv.lock",
    "td_mcp.egg-info/PKG-INFO",
}

OUTPUT_NAME = "SUMMARY.md"

OVERVIEW = """\
# td-mcp — project summary

**td-mcp** is a local-first *TouchDesigner MCP* (Model Context Protocol) toolkit that
fuses the best ideas of the public TD-MCP ecosystem into one cohesive package:

* an **offline documentation / RAG server** (no TouchDesigner required) that answers
  operator / Python / GLSL questions and *generates* networks as diffable YAML;
* a **live bridge + MCP server** that controls a running TouchDesigner session
  (create / wire / inspect / verify) over Streamable-HTTP, SSE, WebSocket or stdio;
* a **naturally embedded chat UI** and a **zero-dependency autonomous agent** that run
  inside TouchDesigner itself.

Everything in ``td_mcp/`` is pure Python (standard library + optional ``mcp`` /
``networkx`` / ``sentence-transformers``) and is fully unit-testable without a
running TouchDesigner. Retrieval quality is provable: an eval harness measures
recall@k / MRR / nDCG over a labelled query set, and the whole project ships with
a regression test suite.

This document lists every tracked file with a one-line purpose — it intentionally
contains **no source code**, only file names, architecture, the tree and per-file
explanations.
"""

def _count_offline_tools() -> int:
    """Count tools registered in the offline server (types.Tool( entries)."""
    p = Path(__file__).resolve().parent.parent / "td_mcp" / "server_offline.py"
    return p.read_text(encoding="utf-8", errors="ignore").count("types.Tool(")


def _count_live_tools() -> int:
    """Count tools in the live server's _TOOL_META registry."""
    p = Path(__file__).resolve().parent.parent / "td_mcp" / "server_live.py"
    txt = p.read_text(encoding="utf-8", errors="ignore")
    return len(re.findall(r'^\s*\("[a-z_]+",\s*"', txt, re.MULTILINE))


ARCHITECTURE = """\
## Architecture

td-mcp is built around **two cooperating servers that share one authoring brain**:

| | Offline server | Live server / bridge |
|---|---|---|
| Module | `td_mcp/server_offline.py` | `td_mcp/server_live.py` + `bridge/td_mcp_bridge.py` |
| Needs TouchDesigner? | **No** | **Yes** (running instance) |
| Role | Doc/RAG answers, network *generation* (YAML, not live nodes), validation, scoring, self-heal | Create / delete / wire / inspect a live TD document over HTTP / stdio |
| Tools | {OFF} (`td_*`) | {LIVE} (`create_node`, `set_parameters`, …) |

The offline side owns the *intelligence*: `generators` -> `validation` ->
`scoring` -> `heal` produce a diffable network description (**TDN** YAML) that the
live bridge materialises inside TD. `tdn` (diffable YAML), `showcontrol` and
`led_mapping` are deterministic pure-Python planning layers; `rag` + `kb` provide
the version-aware retrieval backbone; `tools/` holds cross-cutting risk / recovery /
log / layout helpers.

Three request lifecycles:

1. **Offline doc query** — `server_offline` -> `ParallelRetriever` (global + per-source
   BM25, optional MiniLM dense + HyDE, optional CrossEncoder rerank, optional external
   RAG fused via Reciprocal Rank Fusion) -> ranked chunks.
2. **Offline build + verify** — `_parse_build_spec` -> `td_build_network` (generators)
   -> `td_score_build` -> `td_validate_build` -> `td_self_heal` (no TD needed).
3. **Live mutation** — MCP client -> `server_live` (Streamable HTTP / SSE / stdio) ->
   bridge dispatch table inside TD, every mutation wrapped in `ui.undo` so one
   Ctrl+Z reverts a whole agent batch.

Retrieval is *local-first and version-aware*: the merged MIT corpus
(`td_mcp/kb/corpus/`) plus the hand-authored `chunks.jsonl` back every answer, and
dense / HyDE / rerank paths are lazy (enabled only with `[rag]` + env flags).
""".format(OFF=_count_offline_tools(), LIVE=_count_live_tools())


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def module_docstring(path: Path) -> str:
    """Return the first module-level docstring of a .py file (cleaned)."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.match(r"\s*^\s*\"\"\"(.*?)\"\"\"", text, re.DOTALL)
    if not m:
        # docstring may start after a shebang / encoding line
        m = re.match(r"^(?:#!.*\n)?(?:#.*\n)*\s*\"\"\"(.*?)\"\"\"", text, re.DOTALL)
    if not m:
        return ""
    body = m.group(1).strip()
    # Collapse to the first meaningful paragraph.
    first = body.split("\n\n")[0].strip()
    first = re.sub(r"\s+", " ", first)
    return first


def markdown_summary(path: Path) -> str:
    """Return the first heading + first paragraph of a markdown file."""
    text = path.read_text(encoding="utf-8", errors="replace")
    heading = ""
    para = ""
    for line in text.splitlines():
        if not heading and line.startswith("#"):
            heading = line.lstrip("#").strip()
            continue
        if heading and line.strip() and not line.startswith("#") and not line.startswith(">"):
            para = line.strip()
            break
    out = heading
    if para:
        out += f" — {para}" if out else para
    return out


def toml_summary(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    if "pyproject" in path.name:
        return "Python project metadata: dependencies, optional extras (mcp/rag/scrape) and console entry points (td-mcp-offline, td-mcp-live)."
    return f"Config file ({path.name})."


SUMMARIZERS = {
    ".py": module_docstring,
    ".md": markdown_summary,
    ".toml": toml_summary,
}


def describe(rel: str, path: Path) -> str:
    if rel in FILE_OVERRIDES:
        return FILE_OVERRIDES[rel]
    if rel in DATA_FILES:
        size = path.stat().st_size
        return f"Generated data artifact ({size:,} bytes) — produced by the build/eval pipeline; not hand-edited."
    fn = SUMMARIZERS.get(path.suffix)
    if not fn:
        return "Project file."
    try:
        desc = fn(path)
    except Exception as exc:  # pragma: no cover - defensive
        desc = f"(unreadable: {exc})"
    return desc or "Project file."


def walk_tree() -> tuple[list[str], dict[str, str]]:
    """Return (tree_lines, descriptions) for every summarised file."""
    entries: list[tuple[str, Path]] = []
    descs: dict[str, str] = {}

    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        # never descend into the output's own folder or venv
        for exclude in (".git", ".venv"):
            if exclude in dirnames:
                dirnames.remove(exclude)
        for fn in sorted(filenames):
            p = Path(dirpath) / fn
            rel = str(p.relative_to(ROOT)).replace(os.sep, "/")
            # skip the generated summary itself and lock/pyc noise
            if rel == OUTPUT_NAME or fn.endswith(".pyc") or fn == "uv.lock" and False:
                continue
            if any(rel.startswith(d + "/") for d in EXCLUDE_DIRS):
                continue
            if fn == "uv.lock" or fn.endswith(".egg-info"):
                if rel in DATA_FILES:
                    entries.append((rel, p))
                    descs[rel] = describe(rel, p)
                continue
            if not any(rel.endswith(g.lstrip("*")) or fn.endswith(g.lstrip("*")) for g in INCLUDE_GLOBS):
                # still allow explicitly listed data files
                if rel not in DATA_FILES:
                    continue
            entries.append((rel, p))
            descs[rel] = describe(rel, p)

    entries.sort(key=lambda x: x[0])
    return entries, descs


def render_tree(entries: list[tuple[str, Path]]) -> str:
    """Render a compact, indented ASCII directory tree."""
    paths = [Path(rel) for rel, _ in entries]
    lines: list[str] = []

    # Build a nested representation.
    tree: dict = {}
    for p in paths:
        node = tree
        for part in p.parts:
            node = node.setdefault(part, {})

    def _draw(node: dict, prefix: str):
        # Sort: directories first, then files; keep deterministic.
        items = sorted(node.items(), key=lambda kv: (len(kv[1]) == 0, kv[0].lower()))
        for i, (name, child) in enumerate(items):
            last = i == len(items) - 1
            branch = "└── " if last else "├── "
            lines.append(f"{prefix}{branch}{name}")
            if child:
                _draw(child, prefix + ("    " if last else "│   "))

    lines.append("td-mcp/")
    _draw(tree, "")
    return "\n".join(lines)


def build_summary() -> str:
    entries, descs = walk_tree()

    out = [OVERVIEW, "", ARCHITECTURE, "", "## Directory tree\n", "```", render_tree(entries), "```", ""]
    out.append("## File-by-file explanations\n")
    out.append("*(Each entry names the file and a one-line purpose extracted from the file itself.)*\n")

    # Group by top-level directory for readability.
    groups: dict[str, list[tuple[str, str]]] = {}
    for rel, _ in entries:
        top = rel.split("/", 1)[0] if "/" in rel else "."
        groups.setdefault(top, []).append((rel, descs[rel]))

    order = sorted(groups.keys(), key=lambda k: (k == ".", k))
    for top in order:
        title = "Repository root" if top == "." else f"`{top}/`"
        out.append(f"### {title}\n")
        for rel, desc in groups[top]:
            name = rel.split("/")[-1]
            out.append(f"- **`{rel}`** — {desc}")
        out.append("")

    out.append("---")
    out.append("")
    out.append("*Generated by `scripts/generate_summary.py`. This file contains no source code — "
               "only file names, architecture, the tree and per-file explanations.*")
    return "\n".join(out)


def maybe_run_repomix() -> bool:
    """Optionally emit a full repomix pack if the CLI is available.

    On Windows the ``npx``/``repomix`` launchers ship as ``.ps1``/``.cmd`` files
    that PowerShell's execution policy can block when spawned directly by
    ``CreateProcess``. We therefore go through ``cmd /c`` on Windows, which
    resolves the right wrapper and bypasses the policy.
    """
    repomix = shutil.which("repomix")
    use_npx = repomix is None
    if use_npx:
        repomix = shutil.which("npx")
    if not repomix:
        print("[generate_summary] repomix CLI / npx not found; skipping full pack "
              "(curated SUMMARY.md was still written).", file=sys.stderr)
        return False
    cfg = ROOT / "repomix.config.json"
    if not cfg.exists():
        print("[generate_summary] repomix.config.json missing; skipping full pack.", file=sys.stderr)
        return False

    if use_npx:
        base = ["npx", "--yes", "repomix"]
    else:
        base = ["repomix"]
    args = base + ["--config", str(cfg)]

    if os.name == "nt":
        # Route through cmd.exe so .ps1/.cmd launchers run despite PS policy.
        cmd = ["cmd", "/c", *args]
    else:
        cmd = args

    print(f"[generate_summary] running: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, cwd=str(ROOT), check=True, shell=False)
        return True
    except subprocess.CalledProcessError as exc:
        print(f"[generate_summary] repomix failed: {exc}", file=sys.stderr)
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a code-free td-mcp summary.")
    ap.parse_args()

    summary = build_summary()
    out_path = ROOT / OUTPUT_NAME
    out_path.write_text(summary + "\n", encoding="utf-8")
    print(f"[generate_summary] wrote {out_path.relative_to(ROOT)} "
          f"({len(summary.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
